import { useEffect, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { BarChart3, Download } from 'lucide-react';
import { money, UpgradeButton, WorkspaceCard, WorkspaceError, WorkspaceHeading, WorkspaceSkeleton, workspaceInput, workspaceRequest } from './workspace-ui';

export type Analytics = { days: number; timezone: string; currency: string; advanced: boolean; canViewFinancials: boolean; totals: { orders: number; newCustomers: number; revenue: number | null; averagePaidOrder: number | null }; daily: { date: string; orders: number; paidOrders: number; revenue: number | null }[]; statuses: { status: string; total: number }[]; payments: { status: string; total: number }[]; topProducts: { productId: string | null; name: string; quantity: number; revenue: number | null }[]; topCustomers: { name: string; orders: number; revenue: number }[]; experimentVisits: { variant: string; customers: number }[]; exportEnabled: boolean };
export function OrdersChart({ data, ar }: { data: Analytics['daily']; ar: boolean }) {
  return <div className="mt-5 h-64 w-full" dir="ltr"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{ top: 10, right: 8, bottom: 0, left: -24 }}><defs><linearGradient id="lootbot-order-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#aa9bf4" stopOpacity={0.3}/><stop offset="100%" stopColor="#aa9bf4" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#303b49" strokeDasharray="3 5" vertical={false}/><XAxis dataKey="date" tickFormatter={value => String(value).slice(5)} tick={{ fill: '#97a4af', fontSize: 10 }} axisLine={false} tickLine={false} minTickGap={25}/><YAxis allowDecimals={false} tick={{ fill: '#97a4af', fontSize: 10 }} axisLine={false} tickLine={false}/><Tooltip contentStyle={{ background: '#171f27', border: '1px solid #4b4565', borderRadius: 12 }} labelStyle={{ color: '#e6edec' }}/><Area type="monotone" dataKey="orders" name={ar ? 'الطلبات' : 'Orders'} stroke="#aa9bf4" strokeWidth={2} fill="url(#lootbot-order-fill)"/><Area type="monotone" dataKey="paidOrders" name={ar ? 'مدفوع يدويًا' : 'Marked paid'} stroke="#70dcb5" fill="transparent" strokeWidth={2}/></AreaChart></ResponsiveContainer></div>;
}
const statuses: Record<string, { ar: string; en: string }> = { pending: { ar: 'قيد الانتظار', en: 'Pending' }, confirmed: { ar: 'مؤكد', en: 'Confirmed' }, fulfilled: { ar: 'مكتمل', en: 'Fulfilled' }, cancelled: { ar: 'ملغي', en: 'Cancelled' }, unpaid: { ar: 'غير مدفوع', en: 'Unpaid' }, paid: { ar: 'مدفوع يدويًا', en: 'Marked paid' }, refunded: { ar: 'مسترد يدويًا', en: 'Marked refunded' } };
export function AnalyticsWorkspace({ store, locale = 'ar' }: { store?: { id: string; name: string }; locale?: 'ar' | 'en' }) {
  const ar = locale === 'ar'; const storeId = store?.id ?? ''; const [days, setDays] = useState(30);
  useEffect(()=>setDays(30),[storeId]);
  const query = useQuery({ queryKey: ['analytics', storeId, days], enabled: !!storeId, queryFn: () => workspaceRequest<Analytics>(`/api/stores/${encodeURIComponent(storeId)}/analytics?days=${days}`) });
  const data = query.data;
  if (!store) return <p>{ar ? 'اختر متجرًا أولًا.' : 'Choose a store first.'}</p>;
  return <div className="fade-up"><WorkspaceHeading eyebrow={store.name} title={ar ? 'تحليلات المتجر' : 'Store analytics'} description={ar ? 'الطلبات والعملاء والمدفوعات المسجلة من بيانات متجرك الفعلية. الأيام معروضة بتوقيت UTC.' : 'Orders, customers and recorded payments from your actual store data. Days are shown in UTC.'}><select aria-label={ar ? 'الفترة الزمنية' : 'Date range'} className={`${workspaceInput} !w-auto`} value={days} onChange={event => setDays(Number(event.target.value))}>{[7, 30, ...(data?.advanced ? [90] : [])].map(day => <option key={day} value={day}>{ar ? `آخر ${day} يوم` : `Last ${day} days`}</option>)}</select></WorkspaceHeading>
    {query.isLoading ? <WorkspaceSkeleton/> : query.isError ? <WorkspaceError error={query.error} onRetry={() => void query.refetch()}/> : data && <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[ar ? 'الطلبات' : 'Orders', data.totals.orders], [ar ? 'عملاء جدد' : 'New customers', data.totals.newCustomers], [ar ? 'مدفوعات مسجلة' : 'Recorded payments', data.totals.revenue === null ? (ar ? 'للمالك فقط' : 'Owner only') : money(data.totals.revenue, data.currency, ar)], [ar ? 'متوسط الطلب المدفوع' : 'Average paid order', data.totals.averagePaidOrder === null ? (ar ? 'للمالك فقط' : 'Owner only') : money(data.totals.averagePaidOrder, data.currency, ar)]].map(([label, value]) => <WorkspaceCard key={label} description={String(label)}><p className="mt-4 text-2xl font-bold">{value}</p></WorkspaceCard>)}</div><div className="mt-5 grid gap-5 xl:grid-cols-[1.7fr_1fr]"><WorkspaceCard title={ar ? 'حركة الطلبات' : 'Order activity'} description={ar ? 'تسجيل الطلب والدفع اليدوي خلال الفترة المختارة.' : 'Order creation and manual payment marks during the selected period.'}><OrdersChart data={data.daily} ar={ar}/>{data.totals.orders === 0 && <p className="text-xs text-[#97a4af]">{ar ? 'لا توجد طلبات خلال هذه الفترة.' : 'No orders during this period.'}</p>}</WorkspaceCard><WorkspaceCard title={ar ? 'حالة الطلبات' : 'Order status'}><div className="mt-5 space-y-4">{data.statuses.map(row => <div key={row.status}><div className="flex justify-between text-xs"><span>{statuses[row.status]?.[locale] ?? row.status}</span><strong>{row.total}</strong></div><div className="mt-2 h-2 rounded-full bg-[#303b49]"><div className="h-full rounded-full bg-[#aa9bf4]" style={{ width: `${Math.min(100, row.total / Math.max(1, data.totals.orders) * 100)}%` }}/></div></div>)}{!data.statuses.length && <p className="text-sm text-[#97a4af]">{ar ? 'لا توجد طلبات لعرض حالتها.' : 'No order statuses to show.'}</p>}</div></WorkspaceCard></div>
    {data.advanced ? <div className="mt-5 grid gap-5 lg:grid-cols-2"><WorkspaceCard title={ar ? 'المنتجات الأكثر مبيعًا' : 'Top selling products'} description={ar ? 'تُحتسب الكميات من الطلبات المسجل دفعها فقط.' : 'Quantities are counted from orders marked paid.'}><div className="mt-4 divide-y divide-[#303b49]">{data.topProducts.map((product, index) => <div key={`${product.productId}-${index}`} className="flex flex-wrap items-center justify-between gap-3 py-3 text-sm"><span>{product.name}</span><span className="text-[#97a4af]">{product.quantity} {ar ? 'قطعة' : 'units'}{product.revenue !== null && ` · ${money(product.revenue, data.currency, ar)}`}</span></div>)}{!data.topProducts.length && <p className="py-4 text-sm text-[#97a4af]">{ar ? 'لا توجد مبيعات مسجلة بعد.' : 'No recorded sales yet.'}</p>}</div></WorkspaceCard><WorkspaceCard title={ar ? 'العملاء الأعلى إنفاقًا' : 'Highest spending customers'} description={!data.canViewFinancials ? (ar ? 'هذه البيانات المالية متاحة لمالك المتجر فقط.' : 'Financial data is available to the store owner only.') : undefined}><div className="mt-4 divide-y divide-[#303b49]">{data.topCustomers.map((customer, index) => <div key={index} className="flex flex-wrap justify-between gap-3 py-3 text-sm"><span>{customer.name}</span><span className="text-[#97a4af]">{customer.orders} {ar ? 'طلب' : 'orders'} · {money(customer.revenue, data.currency, ar)}</span></div>)}{data.canViewFinancials && !data.topCustomers.length && <p className="py-4 text-sm text-[#97a4af]">{ar ? 'لا توجد بيانات إنفاق مسجلة.' : 'No recorded customer spending.'}</p>}</div></WorkspaceCard></div> : <WorkspaceCard className="mt-5"><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex gap-3"><BarChart3 className="h-5 w-5 text-[#aa9bf4]"/><div><h2 className="text-sm font-semibold">{ar ? 'تحليلات Business' : 'Business analytics'}</h2><p className="mt-2 text-xs text-[#97a4af]">{ar ? 'المنتجات الأعلى مبيعًا، العملاء الأعلى إنفاقًا، و90 يومًا من الاتجاهات.' : 'Top products, customer spending and 90 days of trends.'}</p></div></div><UpgradeButton ar={ar}/></div></WorkspaceCard>}
    {data.advanced && <WorkspaceCard className="mt-5" title={ar ? 'زيارات تجارب التصميم A/B' : 'A/B design experiment visits'} description={ar ? 'عدد العملاء الفريدين الذين شاهدوا كل نسخة في البوت منذ تفعيل التجربة. قد يظهر العميل في أكثر من نسخة إذا غُيّر التقسيم؛ هذه زيارات تراكمية ولا تعني تحويلات أو إيرادات.' : 'Unique customers who saw each bot variant since the experiment began. A customer can appear in multiple variants after allocation changes. These lifetime visits are not conversions or revenue.'}><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{data.experimentVisits.map(visit => <div key={visit.variant} className="rounded-xl border border-[#303b49] bg-[#11191f] p-4"><p className="text-xs text-[#97a4af]" dir="ltr">{visit.variant}</p><p className="mt-3 text-xl font-bold">{visit.customers}</p><p className="mt-2 text-xs text-[#97a4af]">{ar ? 'عميل فريد' : 'unique customers'}</p></div>)}{!data.experimentVisits.length && <p className="text-sm text-[#97a4af]">{ar ? 'لم تُسجّل زيارات لتجارب تصميم منشورة بعد.' : 'No published design experiment visits recorded yet.'}</p>}</div></WorkspaceCard>}
    {data.exportEnabled && <a className="mt-5 inline-flex items-center gap-2 rounded-xl border border-[#354344] px-4 py-3 text-sm" href={`/api/stores/${encodeURIComponent(storeId)}/reports/orders.csv`}><Download className="h-4 w-4"/>{ar ? 'تنزيل تقرير الطلبات الكامل' : 'Export complete order report'}</a>}<p className="mt-5 text-xs leading-7 text-[#97a4af]">{ar ? 'LootBot لا يعالج دفعات مالية. الإيراد يعني المبالغ التي سجّل المتجر استلامها يدويًا؛ استرداد المبلغ يزيله من الإيراد.' : 'LootBot does not process payments. Revenue means payments the store marked received manually; refunded payments are excluded.'}</p></>}
  </div>;
}
