import { useEffect, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { useGetCsrfToken } from '@workspace/api-client-react';
import { UpgradeButton, workspaceButton, workspaceInput, workspaceRequest } from './workspace-ui';
type Presentation = { imageUrl: string | null; emoji: string };
export function CategoryPresentation({ categoryId, enabled = true, locale = 'ar' }: { categoryId: string; enabled?: boolean; locale?: 'ar' | 'en' }) {
  const ar = locale === 'ar'; const csrf = useGetCsrfToken(); const [value,setValue]=useState<Presentation>({imageUrl:null,emoji:'📂'});
  const [error,setError]=useState('');const [notice,setNotice]=useState('');const [pending,setPending]=useState(false);const [imageFailed,setImageFailed]=useState(false);
  const query=useQuery({queryKey:['category-presentation',categoryId],enabled:!!categoryId,queryFn:()=>workspaceRequest<Presentation>(`/api/categories/${encodeURIComponent(categoryId)}/presentation`)});
  useEffect(()=>{if(query.data)setValue(query.data);setError('');setNotice('');setImageFailed(false);},[query.data,categoryId]);
  async function save(){
    if(!enabled||pending||!csrf.data?.token)return;setPending(true);setError('');setNotice('');
    try{const response=await fetch(`/api/categories/${encodeURIComponent(categoryId)}/presentation`,{method:'PUT',credentials:'include',headers:{'content-type':'application/json','x-csrf-token':csrf.data.token},body:JSON.stringify(value)});const payload=await response.json();if(!response.ok)throw new Error(payload.error??'Request failed');await query.refetch();setNotice(ar?'حُفظت صورة التصنيف ورمزه. يستخدمهما تصميم البوت عند اختيار العرض المناسب.':'Category image and emoji saved. Your selected bot layout uses this presentation.');}
    catch(cause){setError(cause instanceof Error?cause.message:'Request failed');}finally{setPending(false);}
  }
  return <section className="mt-5 space-y-4 border-t border-[#303b49] pt-5"><h3 className="text-sm font-semibold">{ar?'صورة التصنيف ورمزه':'Category image and emoji'}</h3><p className="text-xs leading-6 text-[#97a4af]">{ar?'إعداد مستقل محفوظ للتصنيف. اختر شبكة الصور أو الرموز في مصمم البوت لعرضه للعملاء.':'Saved independently for this category. Choose an image or emoji grid in the bot designer to show it to customers.'}</p>
    {query.isLoading?<div className="h-20 animate-pulse rounded-xl bg-[#303b49]/30"/>:query.isError?<button type="button" className={workspaceButton} onClick={()=>void query.refetch()}>{ar?'تعذر التحميل. إعادة المحاولة':'Could not load. Retry'}</button>:<>
      {!enabled&&<div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[#4b4565] bg-[#211d35]/40 p-3"><span className="text-xs text-[#c8bcff]">{ar?'تخصيص التصنيفات متاح في Pro وBusiness.':'Category presentation requires Pro or Business.'}</span><UpgradeButton ar={ar} requiredPlan="PRO"/></div>}
      <fieldset disabled={!enabled||pending||!csrf.data?.token} className="space-y-4"><label className="block text-xs">{ar?'الرمز التعبيري':'Emoji'}<input className={`${workspaceInput} mt-2`} value={value.emoji} maxLength={20} onChange={event=>setValue({...value,emoji:event.target.value})}/></label><label className="block text-xs">{ar?'رابط صورة HTTPS (اختياري)':'HTTPS image URL (optional)'}<input className={`${workspaceInput} mt-2`} type="url" value={value.imageUrl??''} maxLength={1500} placeholder="https://…" onChange={event=>{setValue({...value,imageUrl:event.target.value||null});setImageFailed(false);}}/></label><div className="flex items-center gap-4 rounded-xl border border-[#303b49] bg-[#11191f] p-3">{value.imageUrl&&!imageFailed?<img src={value.imageUrl} alt={ar?'معاينة صورة التصنيف':'Category image preview'} referrerPolicy="no-referrer" className="h-16 w-16 rounded-xl object-cover" onError={()=>setImageFailed(true)}/>:<span className="grid h-16 w-16 place-items-center rounded-xl bg-[#aa9bf4]/10 text-3xl">{value.emoji||'📂'}</span>}<p className="text-xs leading-6 text-[#97a4af]">{imageFailed?(ar?'تعذر تحميل الصورة. سيبقى الرمز بديلًا آمنًا.':'The image could not load. The emoji remains a safe fallback.'):(ar?'معاينة الصورة والرمز المحفوظين لهذا التصنيف.':'Preview of this category image and emoji.')}</p></div><button type="button" className={workspaceButton} onClick={()=>void save()}>{pending?(ar?'جار الحفظ…':'Saving…'):(ar?'حفظ عرض التصنيف':'Save category presentation')}</button></fieldset>
    </>}{error&&<p role="alert" className="text-sm text-[#e4a09a]">{error}</p>}{notice&&<p role="status" className="text-xs leading-6 text-[#70dcb5]">{notice}</p>}
  </section>;
}
