import { useEffect, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { useGetCsrfToken } from '@workspace/api-client-react';

type Preferences = { cartEnabled: boolean; favoritesEnabled: boolean; pointsEnabled: boolean; referralsEnabled: boolean; couponsEnabled: boolean; reviewsEnabled: boolean; supportEnabled: boolean; supportUsername: string; pointsPerPaidOrder: number; referralRewardPoints: number };
type Coupon = { id?: string; code: string; percent: number; minimum: number | string; maxUses: number; uses?: number; expiresAt: string | null; enabled: boolean };
type Commerce = { editable: boolean; preferences: Preferences; entitlements?: Record<string, boolean>; availability: Record<string, boolean>; coupons: Coupon[]; reviews: { id: string; stars: number; customerName?: string; productName?: string; createdAt: string }[] };
const input = 'mt-2 w-full rounded-lg border border-[#354344] bg-[#182123] p-2 text-sm';
const button = 'rounded-lg border border-[#354344] px-3 py-2 text-sm disabled:opacity-40';
const emptyCoupon = (): Coupon => ({ code: '', percent: 10, minimum: 0, maxUses: 100, enabled: true, expiresAt: null });
const preferenceFlags = ['cartEnabled', 'favoritesEnabled', 'pointsEnabled', 'referralsEnabled', 'couponsEnabled', 'reviewsEnabled', 'supportEnabled'] as const;

export function CommerceWorkspace({ store, locale = 'ar' }: { store?: { id: string }; locale?: 'ar' | 'en' }) {
  const ar = locale === 'ar'; const storeId = store?.id ?? ''; const csrf = useGetCsrfToken();
  const [preferences, setPreferences] = useState<Preferences | null>(null); const [coupon, setCoupon] = useState<Coupon>(emptyCoupon); const [pending, setPending] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const request = async (path: string, method = 'GET', body?: unknown) => {
    const response = await fetch(`/api/stores/${encodeURIComponent(storeId)}/commerce${path}`, { method, credentials: 'include', headers: { 'content-type': 'application/json', ...(csrf.data?.token ? { 'x-csrf-token': csrf.data.token } : {}) }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
    const data = await response.json(); if (!response.ok) throw new Error(data.error || (ar ? 'تعذر إكمال الطلب.' : 'Request failed.')); return data;
  };
  const commerce = useQuery({ queryKey: ['commerce', storeId], enabled: !!storeId, queryFn: () => request('') as Promise<Commerce> });
  const redemptions = useQuery({ queryKey: ['commerce-redemptions', storeId], enabled: !!storeId && !!commerce.data?.entitlements?.coupons, queryFn: () => request('/redemptions') as Promise<{ id: string; code: string; orderId: string; discount: string; customerName?: string; createdAt: string }[]> });
  useEffect(() => { setPreferences(null); setCoupon(emptyCoupon()); setError(''); setNotice(''); }, [storeId]);
  useEffect(() => { if (commerce.data) setPreferences(commerce.data.preferences); }, [commerce.data]);
  const labels: Record<(typeof preferenceFlags)[number], string> = ar ? { cartEnabled: 'سلة الشراء', favoritesEnabled: 'المفضلة', pointsEnabled: 'النقاط', referralsEnabled: 'الإحالات', couponsEnabled: 'الكوبونات', reviewsEnabled: 'تقييمات المشترين', supportEnabled: 'دعم العملاء' } : { cartEnabled: 'Cart', favoritesEnabled: 'Favorites', pointsEnabled: 'Points', referralsEnabled: 'Referrals', couponsEnabled: 'Coupons', reviewsEnabled: 'Verified buyer reviews', supportEnabled: 'Customer support' };
  const capability = (flag: string) => flag.replace(/Enabled$/, '');
  async function run(operation: () => Promise<unknown>, message: string) {
    if (!csrf.data?.token || pending) return; setPending(true); setError(''); setNotice('');
    try { await operation(); await commerce.refetch(); if (redemptions.isEnabled) await redemptions.refetch(); setNotice(message); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Request failed.'); } finally { setPending(false); }
  }
  if (!storeId) return <p>{ar ? 'اختر متجرًا أولًا.' : 'Choose a store first.'}</p>;
  return <section className="space-y-5"><header><h1 className="text-3xl font-semibold">{ar ? 'ميزات العملاء' : 'Customer features'}</h1><p className="mt-2 text-sm text-[#94a0ad]">{ar ? 'السلة والكوبونات والنقاط والإحالات والتقييمات مرتبطة بالطلبات الحقيقية في متجرك.' : 'Cart, coupons, points, referrals and reviews use your real customer orders.'}</p></header>
    {error && <p role="alert" className="rounded-xl border border-[#694141] p-3 text-[#e4a09a]">{error}</p>}{notice && <p role="status" className="text-sm text-[#85dabc]">{notice}</p>}
    {commerce.isLoading ? <p>{ar ? 'جار التحميل…' : 'Loading…'}</p> : commerce.isError ? <button className={button} onClick={() => void commerce.refetch()}>{ar ? 'تعذر تحميل البيانات. إعادة المحاولة' : 'Could not load data. Retry'}</button> : preferences && <>
      {!commerce.data?.editable && <p className="rounded-xl border border-[#66543b] p-4 text-sm text-[#e5c996]">{ar ? 'هذه الميزات متاحة في Pro وBusiness حسب صلاحيات باقتك.' : 'These features require Pro or Business according to plan entitlements.'}</p>}
      <div className="grid gap-5 xl:grid-cols-2"><section className="space-y-4 rounded-xl border border-[#354344] bg-[#171f27] p-5"><h2 className="font-semibold">{ar ? 'إعدادات العملاء' : 'Customer preferences'}</h2><fieldset disabled={pending || !csrf.data?.token || !commerce.data?.editable} className="space-y-4">
        <div className="grid gap-3 sm:grid-cols-2">{preferenceFlags.map(flag => <label key={flag} className="flex items-center justify-between gap-3 rounded-lg border border-[#354344] p-3 text-sm"><span>{labels[flag]}{commerce.data?.entitlements && !commerce.data.entitlements[capability(flag)] && <span className="ms-2 text-xs text-[#e5c996]">{ar ? 'غير متاحة في الباقة' : 'Plan locked'}</span>}</span><input type="checkbox" checked={preferences[flag]} disabled={!!commerce.data?.entitlements && !commerce.data.entitlements[capability(flag)]} onChange={event => setPreferences({ ...preferences, [flag]: event.target.checked })}/></label>)}</div>
        <label className="block text-sm">{ar ? 'نقاط لكل طلب مدفوع' : 'Points per paid order'}<input type="number" min={0} max={100000} className={input} value={preferences.pointsPerPaidOrder} onChange={event => setPreferences({ ...preferences, pointsPerPaidOrder: Number(event.target.value) })}/></label>
        <label className="block text-sm">{ar ? 'نقاط صاحب الإحالة بعد أول طلب مدفوع للعميل الجديد' : 'Referrer points after the new customer’s first paid order'}<input type="number" min={0} max={100000} className={input} value={preferences.referralRewardPoints} onChange={event => setPreferences({ ...preferences, referralRewardPoints: Number(event.target.value) })}/></label>
        <label className="block text-sm">{ar ? 'اسم حساب الدعم في Telegram، بدون @' : 'Telegram support username, without @'}<input className={input} maxLength={32} value={preferences.supportUsername} onChange={event => setPreferences({ ...preferences, supportUsername: event.target.value.replace(/^@/, '') })}/></label>
        <button type="button" className={button + ' bg-[#26483c] text-[#85dabc]'} onClick={() => void run(() => request('/preferences', 'PATCH', preferences), ar ? 'تم حفظ ميزات العملاء.' : 'Customer preferences saved.')}>{ar ? 'حفظ الإعدادات' : 'Save preferences'}</button>
      </fieldset><p className="text-xs leading-6 text-[#94a0ad]">{ar ? 'المكافأة تصدر مرة واحدة عند تأكيد الدفع. استرداد الطلب يلغي النقاط التي لا تزال في الرصيد. تغيير الإعدادات لا يمنح مكافآت للطلبات السابقة. التقييم متاح فقط لمشتري المنتج الذي دفع قيمته.' : 'Rewards are granted once on payment. Refunds reverse points still in the balance. Changes do not reward past orders. Reviews require a paid purchase.'}</p></section>
      <section className="space-y-4 rounded-xl border border-[#354344] bg-[#171f27] p-5"><h2 className="font-semibold">{coupon.id ? (ar ? 'تعديل الكوبون' : 'Edit coupon') : (ar ? 'كوبون جديد' : 'New coupon')}</h2><fieldset disabled={pending || !csrf.data?.token || !commerce.data?.entitlements?.coupons} className="space-y-4">
        <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">{ar ? 'الرمز' : 'Code'}<input className={input} dir="ltr" maxLength={24} value={coupon.code} onChange={event => setCoupon({ ...coupon, code: event.target.value.toUpperCase() })}/></label><label className="text-sm">{ar ? 'نسبة الخصم' : 'Discount percent'}<input type="number" min={1} max={100} className={input} value={coupon.percent} onChange={event => setCoupon({ ...coupon, percent: Number(event.target.value) })}/></label><label className="text-sm">{ar ? 'أقل مبلغ للطلب' : 'Minimum order amount'}<input type="number" min={0} max={9999999999} step="0.01" className={input} value={coupon.minimum} onChange={event => setCoupon({ ...coupon, minimum: Number(event.target.value) })}/></label><label className="text-sm">{ar ? 'الحد الكلي للاستخدام' : 'Total usage limit'}<input type="number" min={Math.max(1, coupon.uses ?? 0)} max={1000000} className={input} value={coupon.maxUses} onChange={event => setCoupon({ ...coupon, maxUses: Number(event.target.value) })}/></label></div>
        <label className="block text-sm">{ar ? 'ينتهي في (بتوقيت UTC؛ فارغ بدون نهاية)' : 'Expires at (UTC; empty means no expiry)'}<input type="datetime-local" className={input} value={coupon.expiresAt?.slice(0, 16) ?? ''} onChange={event => setCoupon({ ...coupon, expiresAt: event.target.value ? new Date(event.target.value + ':00.000Z').toISOString() : null })}/></label>
        <label className="flex gap-2 text-sm"><input type="checkbox" checked={coupon.enabled} onChange={event => setCoupon({ ...coupon, enabled: event.target.checked })}/>{ar ? 'مفعّل' : 'Enabled'}</label>
        <div className="flex gap-3"><button type="button" className={button} disabled={!coupon.code.trim()} onClick={() => void run(async () => { await request('/coupons', 'POST', { ...coupon, minimum: Number(coupon.minimum) }); setCoupon(emptyCoupon()); }, ar ? 'تم حفظ الكوبون.' : 'Coupon saved.')}>{ar ? 'حفظ الكوبون' : 'Save coupon'}</button><button type="button" className={button} onClick={() => setCoupon(emptyCoupon())}>{ar ? 'كوبون جديد' : 'New coupon'}</button></div>
      </fieldset><p className="text-xs leading-6 text-[#94a0ad]">{ar ? 'يختار العميل كوبونًا بإرسال /coupon الرمز. يُطبّق على السلة وقت التأكيد. الاستخدام مرة واحدة لكل عميل؛ يتوقف الكوبون عند انتهاء الوقت أو نفاد العدد.' : 'Customers select a coupon using /coupon CODE. It applies at cart checkout once per customer and stops at its expiry or total usage limit.'}</p></section></div>
      <section className="overflow-x-auto rounded-xl border border-[#354344] p-5"><h2 className="font-semibold">{ar ? 'الكوبونات المحفوظة' : 'Saved coupons'}</h2><table className="mt-4 w-full min-w-[550px] text-sm"><thead><tr className="text-[#94a0ad]"><th className="p-3 text-start">{ar ? 'الرمز' : 'Code'}</th><th>{ar ? 'الخصم' : 'Discount'}</th><th>{ar ? 'الاستخدام' : 'Usage'}</th><th>{ar ? 'الحالة' : 'Status'}</th><th/></tr></thead><tbody>{commerce.data?.coupons.map(saved => <tr key={saved.id} className="border-t border-[#354344]"><td className="p-3" dir="ltr">{saved.code}</td><td className="text-center">{saved.percent}%</td><td className="text-center">{saved.uses ?? 0}/{saved.maxUses}</td><td className="text-center">{!saved.enabled ? (ar ? 'موقوف' : 'Disabled') : saved.expiresAt && new Date(saved.expiresAt).getTime() <= Date.now() ? (ar ? 'منتهٍ' : 'Expired') : (saved.uses ?? 0) >= saved.maxUses ? (ar ? 'نفد العدد' : 'Exhausted') : (ar ? 'مفعّل' : 'Enabled')}</td><td className="p-3"><button className={button} disabled={pending || !commerce.data?.entitlements?.coupons} onClick={() => setCoupon({ ...saved })}>{ar ? 'تعديل' : 'Edit'}</button></td></tr>)}</tbody></table>{!commerce.data?.coupons.length && <p className="py-4 text-sm text-[#94a0ad]">{ar ? 'لا توجد كوبونات محفوظة.' : 'No saved coupons.'}</p>}</section>
      {commerce.data?.entitlements?.coupons && <section className="rounded-xl border border-[#354344] p-5"><h2 className="font-semibold">{ar ? 'استخدام الكوبونات' : 'Coupon redemptions'}</h2>{redemptions.isError ? <button className={button} onClick={() => void redemptions.refetch()}>{ar ? 'تعذر تحميل السجل. إعادة المحاولة' : 'Could not load history. Retry'}</button> : redemptions.isLoading ? <p className="mt-4 text-sm">{ar ? 'جار التحميل…' : 'Loading…'}</p> : redemptions.data?.length ? redemptions.data.map(row => <div key={row.id} className="mt-3 border-t border-[#354344] pt-3 text-sm">{row.code} · {row.customerName} · {ar ? 'طلب' : 'Order'} {row.orderId.slice(0, 8)} · {ar ? 'خصم' : 'Discount'} {row.discount}</div>) : <p className="mt-4 text-sm text-[#94a0ad]">{ar ? 'لم يُستخدم أي كوبون بعد.' : 'No coupon has been redeemed yet.'}</p>}</section>}
      <section className="rounded-xl border border-[#354344] p-5"><h2 className="font-semibold">{ar ? 'أحدث تقييمات المشترين' : 'Latest verified buyer reviews'}</h2>{commerce.data?.reviews.length ? commerce.data.reviews.map(review => <div key={review.id} className="mt-3 border-t border-[#354344] pt-3 text-sm">{'★'.repeat(review.stars)}{'☆'.repeat(5 - review.stars)} · {review.productName} · {review.customerName}</div>) : <p className="mt-4 text-sm text-[#94a0ad]">{ar ? 'لا توجد تقييمات بعد.' : 'No reviews yet.'}</p>}</section>
    </>}
  </section>;
}
