import { useEffect, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
export type GrowthButton = { text: string; type: 'OPEN_URL' | 'OPEN_PRODUCT' | 'OPEN_CATEGORY' | 'OPEN_HOME'; target: string };
export type GrowthAudience = { type: 'all' | 'segment' | 'vip' | 'inactive' | 'highSpend' | 'selected'; segmentId: string; minimum: number; inactivityDays: number; customerIds: string[] };
const input = 'mt-2 w-full rounded-lg border border-[#354344] bg-[#182123] p-2 text-sm';
const button = 'rounded-lg border border-[#354344] px-3 py-2 text-sm disabled:opacity-40';
export const actionLabels: Record<string, string> = { SEND_MESSAGE: 'إرسال رسالة', SEND_PRODUCT: 'إرسال منتج', SEND_CATEGORY: 'إرسال تصنيف', SEND_COUPON: 'تقديم كوبون', ADD_POINTS: 'إضافة نقاط', REMOVE_POINTS: 'خصم نقاط', ADD_TAG: 'إضافة وسم', REMOVE_TAG: 'إزالة وسم', ADD_SEGMENT: 'إضافة لشريحة', REMOVE_SEGMENT: 'إزالة من شريحة', NOTIFY_ADMIN: 'إشعار المسؤول' };
export const triggerLabels: Record<string, string> = { USER_REGISTERED: 'بدء عميل جديد', ORDER_CREATED: 'إنشاء طلب', ORDER_PAID: 'دفع الطلب', ORDER_FULFILLED: 'إكمال الطلب', ORDER_CANCELLED: 'إلغاء الطلب', COUPON_USED: 'استخدام كوبون', POINTS_EARNED: 'اكتساب نقاط', REFERRAL_COMPLETED: 'اكتمال إحالة', REVIEW_CREATED: 'كتابة تقييم', VIP_LEVEL_CHANGED: 'تغيير مستوى VIP', USER_INACTIVE: 'عدم نشاط العميل', SCHEDULED_TIME: 'وقت محدد' };
export const statusLabels: Record<string, string> = { draft: 'مسودة', queued: 'بانتظار التنفيذ', running: 'قيد التنفيذ', completed: 'مكتمل', failed: 'فشل', cancelled: 'متوقف' };
export const newAudience = (): GrowthAudience => ({ type: 'all', segmentId: '', minimum: 1, inactivityDays: 14, customerIds: [] });
export const targetKind = (type: string) => type.includes('PRODUCT') ? 'products' : type.includes('CATEGORY') ? 'categories' : type.includes('COUPON') ? 'coupons' : 'segments';
export function GrowthTargetPicker({ storeId, kind, value, ar, onChange }: { storeId: string; kind: string; value: string; ar: boolean; onChange: (value: string, label?: string) => void }) {
  const [query, setQuery] = useState(''); const [page, setPage] = useState(1); const [labels, setLabels] = useState<Record<string, string>>({});
  useEffect(() => { setQuery(''); setPage(1); setLabels({}); }, [storeId, kind]);
  const options = useQuery({ queryKey: ['growth-options', storeId, kind, query, page, value], queryFn: async () => {
    const response = await fetch(`/api/stores/${encodeURIComponent(storeId)}/growth/options/${kind}?q=${encodeURIComponent(query)}&page=${page}&selected=${encodeURIComponent(value)}`, { credentials: 'include' });
    const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Could not load choices'); return data as { options: { value: string; label: string }[]; hasMore: boolean; selectedOption: { value: string; label: string } | null };
  } });
  useEffect(() => { if (options.data) setLabels(previous => ({ ...previous, ...Object.fromEntries([...options.data.options, ...(options.data.selectedOption ? [options.data.selectedOption] : [])].map(o => [o.value, o.label])) })); }, [options.data]);
  return <div className="space-y-2"><input aria-label={ar ? 'البحث في الأهداف' : 'Search targets'} placeholder={ar ? 'ابحث بالاسم' : 'Search by name'} maxLength={100} className={input} value={query} onChange={e => { setQuery(e.target.value); setPage(1); }}/>{options.isError ? <button type="button" className={button} onClick={() => void options.refetch()}>{ar ? 'تعذر تحميل الخيارات. أعد المحاولة' : 'Could not load choices. Retry'}</button> : <select aria-label={ar ? 'الهدف' : 'Target'} className={input} value={value} onChange={e => onChange(e.target.value, labels[e.target.value])}><option value="">{options.isLoading ? ar ? 'جار التحميل…' : 'Loading…' : ar ? 'اختر الهدف' : 'Choose target'}</option>{value && !options.data?.options.some(o => o.value === value) && <option value={value}>{labels[value] || (ar ? 'الهدف المحفوظ؛ ابحث عنه للتحقق' : 'Saved target; search to verify')}</option>}{options.data?.options.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}</select>}{!options.isLoading && !options.isError && !options.data?.options.length && <p className="text-xs text-[#94a0ad]">{ar ? 'لا توجد خيارات متاحة تطابق البحث.' : 'No available choices match your search.'}</p>}{(page > 1 || options.data?.hasMore) && <div className="flex gap-2"><button type="button" className={button} disabled={page === 1} onClick={() => setPage(page - 1)}>{ar ? 'السابق' : 'Previous'}</button><button type="button" className={button} disabled={!options.data?.hasMore} onClick={() => setPage(page + 1)}>{ar ? 'التالي' : 'Next'}</button></div>}</div>;
}
export function GrowthAudienceEditor({ storeId, value, ar, onChange }: { storeId: string; value: GrowthAudience; ar: boolean; onChange: (next: GrowthAudience) => void }) {
  const [names, setNames] = useState<Record<string, string>>({});
  const selected = useQuery({ queryKey: ['growth-selected-customer-names', storeId, value.customerIds], enabled: value.type === 'selected' && value.customerIds.length > 0, queryFn: async () => {
    const pages = Array.from({ length: Math.ceil(value.customerIds.length / 50) }, (_, page) => value.customerIds.slice(page * 50, (page + 1) * 50));
    const results = await Promise.all(pages.map(async ids => { const response = await fetch(`/api/stores/${encodeURIComponent(storeId)}/growth/customer-labels?ids=${encodeURIComponent(ids.join(','))}`, { credentials: 'include' }); if (!response.ok) throw new Error('Could not load selected customers'); return await response.json() as { id: string; name: string; optedIn: boolean }[]; }));
    return Object.fromEntries(results.flat().map(customer => [customer.id, customer.name + (!customer.optedIn ? ar ? ' (موقوف)' : ' (stopped)' : '')]));
  } });
  useEffect(() => { if (selected.data) setNames(previous => ({ ...previous, ...selected.data })); }, [selected.data]);
  const labels: Record<string, string> = { all: 'كل العملاء', segment: 'شريحة', vip: 'عملاء VIP', inactive: 'العملاء غير النشطين', highSpend: 'أعلى إنفاقًا', selected: 'عملاء محددون' };
  return <div className="space-y-3"><label className="block text-sm">{ar ? 'الجمهور' : 'Audience'}<select className={input} value={value.type} onChange={e => onChange({ ...newAudience(), type: e.target.value as GrowthAudience['type'] })}>{Object.entries(labels).map(([key, label]) => <option key={key} value={key}>{ar ? label : key}</option>)}</select></label>
    {value.type === 'segment' && <GrowthTargetPicker storeId={storeId} kind="segments" value={value.segmentId} ar={ar} onChange={segmentId => onChange({ ...value, segmentId })}/>}
    {['vip', 'highSpend'].includes(value.type) && <label className="block text-xs">{ar ? value.type === 'vip' ? 'الحد الأدنى لمستوى VIP' : 'الحد الأدنى لإجمالي المدفوع' : 'Minimum level or spend'}<input type="number" min={0} className={input} value={value.minimum} onChange={e => onChange({ ...value, minimum: Number(e.target.value) })}/></label>}
    {value.type === 'inactive' && <label className="block text-xs">{ar ? 'أيام عدم النشاط' : 'Inactive days'}<input type="number" min={1} max={365} className={input} value={value.inactivityDays} onChange={e => onChange({ ...value, inactivityDays: Number(e.target.value) })}/></label>}
    {value.type === 'selected' && <><GrowthTargetPicker storeId={storeId} kind="customers" value="" ar={ar} onChange={(id, label) => { if (!id || value.customerIds.includes(id) || value.customerIds.length >= 500) return; setNames({ ...names, [id]: label ?? '' }); onChange({ ...value, customerIds: [...value.customerIds, id] }); }}/><div className="flex flex-wrap gap-2">{value.customerIds.map((id, i) => <button key={id} type="button" className={button} onClick={() => onChange({ ...value, customerIds: value.customerIds.filter(v => v !== id) })}>{names[id] || (ar ? `عميل مختار ${i + 1}` : `Selected customer ${i + 1}`)} ×</button>)}</div><p className="text-xs text-[#94a0ad]">{ar ? `${value.customerIds.length} من 500 عميل مختار` : `${value.customerIds.length} of 500 selected customers`}</p></>}
  </div>;
}
export function GrowthButtonsEditor({ storeId, value, ar, onChange }: { storeId: string; value: GrowthButton[]; ar: boolean; onChange: (next: GrowthButton[]) => void }) {
  const labels: Record<GrowthButton['type'], string> = { OPEN_URL: 'رابط خارجي', OPEN_PRODUCT: 'منتج', OPEN_CATEGORY: 'تصنيف', OPEN_HOME: 'الرئيسية' };
  const change = (index: number, next: GrowthButton) => onChange(value.map((b, i) => i === index ? next : b));
  return <div className="space-y-2"><h4 className="text-xs">{ar ? 'أزرار الرسالة' : 'Message buttons'}</h4>{value.map((b, index) => <div key={index} className="space-y-2 rounded-lg bg-[#111925] p-3"><input aria-label={ar ? 'اسم الزر' : 'Button label'} maxLength={48} className={input} value={b.text} onChange={e => change(index, { ...b, text: e.target.value })}/><select className={input} value={b.type} onChange={e => change(index, { ...b, type: e.target.value as GrowthButton['type'], target: '' })}>{Object.entries(labels).map(([type, label]) => <option key={type} value={type}>{ar ? label : type.toLowerCase().replaceAll('_', ' ')}</option>)}</select>{b.type === 'OPEN_URL' ? <input type="url" placeholder="https://" className={input} value={b.target} onChange={e => change(index, { ...b, target: e.target.value })}/> : b.type !== 'OPEN_HOME' && <GrowthTargetPicker storeId={storeId} kind={targetKind(b.type)} value={b.target} ar={ar} onChange={target => change(index, { ...b, target })}/>}<button type="button" className={button} onClick={() => onChange(value.filter((_, i) => i !== index))}>{ar ? 'حذف الزر' : 'Remove button'}</button></div>)}<button type="button" className={button} disabled={value.length >= 8} onClick={() => onChange([...value, { text: ar ? 'تصفح المتجر' : 'Visit store', type: 'OPEN_HOME', target: '' }])}>{ar ? '+ زر' : '+ Button'}</button></div>;
}
