import { useQuery } from '@tanstack/react-query';
import { Link } from 'wouter';
import { Activity, ArrowUpRight, CircleDollarSign, MessageCircle, Package, Plus, ShoppingBag, Users } from 'lucide-react';
import { money, WorkspaceCard, WorkspaceError, WorkspaceHeading, WorkspaceSkeleton, workspaceRequest } from './workspace-ui';
import { OrdersChart, type Analytics } from './analytics-workspace';
import { useWorkspaceSummary } from './workspace-summary';
import { PlanUsage } from './plan-usage';

const orderStatus: Record<string, { ar: string; en: string }> = { pending: { ar: 'بانتظار التجهيز', en: 'Pending' }, confirmed: { ar: 'مؤكد', en: 'Confirmed' }, fulfilled: { ar: 'مكتمل', en: 'Fulfilled' }, cancelled: { ar: 'ملغي', en: 'Cancelled' } };
export function OverviewWorkspace({ store, locale = 'ar', userName = '', permissions=[] }: { store?: { id: string; name: string; currency: string }; locale?: 'ar' | 'en'; userName?: string; permissions?:string[] }) {
  const ar = locale === 'ar'; const query = useWorkspaceSummary(store?.id ?? ''); const data = query.data;
  const canAnalytics=data?.isOwner===true||permissions.includes('analytics.read');
  const trend=useQuery({queryKey:['analytics',store?.id,7],enabled:!!store&&canAnalytics,queryFn:()=>workspaceRequest<Analytics>(`/api/stores/${encodeURIComponent(store!.id)}/analytics?days=7`)});
  if (!store) return <WorkspaceCard title={ar ? 'ابدأ بمتجرك الأول' : 'Start your first store'} description={ar ? 'أضف اسم المتجر، ثم جهز الكتالوج واربط البوت.' : 'Create a store, prepare the catalog and connect your bot.'}><Link href="/dashboard/stores" className="mt-5 inline-flex rounded-xl bg-[#aa9bf4] px-5 py-3 font-semibold text-[#161329]">{ar ? 'إنشاء متجر' : 'Create store'}</Link></WorkspaceCard>;
  return <div className="fade-up"><div className="console-welcome mb-6"><WorkspaceHeading eyebrow={ar ? `أهلاً ${userName}` : `Welcome ${userName}`} title={store.name} description={ar ? 'صورة واضحة لمتجرك اليوم، وخطوتك التالية في مكان واحد.' : 'A clear picture of your store and the next steps in one place.'}><Link href="/dashboard/telegram" className={`inline-flex items-center gap-2 rounded-full border px-4 py-2 text-xs ${data?.telegram.live ? 'border-[#32614e] bg-[#1b342a] text-[#7fddb8]' : 'border-[#594b37] bg-[#30291f] text-[#e0b87d]'}`}><span className={`h-2 w-2 rounded-full ${data?.telegram.live ? 'bg-[#70dcb5]' : 'bg-[#e0b87d]'}`}/>{query.isLoading ? (ar ? 'فحص حالة البوت…' : 'Loading bot status…') : data?.telegram.live ? (ar ? 'البوت يعمل' : 'Bot is active') : data?.telegram.linked ? (ar ? 'الاستقبال يحتاج مراجعة' : 'Polling needs attention') : (ar ? 'البوت غير مربوط' : 'Bot not connected')}</Link></WorkspaceHeading></div>
    {query.isLoading ? <WorkspaceSkeleton/> : query.isError ? <WorkspaceError error={query.error} onRetry={() => void query.refetch()}/> : data && <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[{ title: ar ? 'المدفوعات المسجلة' : 'Recorded payments', value: data.revenue === null ? (ar ? 'متاحة للمالك' : 'Owner only') : money(data.revenue, store.currency, ar), detail: ar ? 'استلام يدوي، بعد استبعاد المسترد' : 'Manual receipts, refunds excluded', icon: CircleDollarSign, color: '#70dcb5' }, { title: ar ? 'كل الطلبات' : 'All orders', value: data.orderCount, detail: ar ? `${data.pendingOrders} بانتظار التجهيز` : `${data.pendingOrders} pending fulfillment`, icon: ShoppingBag, color: '#aa9bf4' }, { title: ar ? 'المنتجات' : 'Products', value: data.usage.productsPerStore, detail: ar ? `${data.publishedProducts} منشور في المتجر` : `${data.publishedProducts} published`, icon: Package, color: '#e0b87d' }, { title: ar ? 'العملاء' : 'Customers', value: data.customers, detail: ar ? `${data.optedInCustomers} يسمحون برسائل البوت` : `${data.optedInCustomers} opted in to messages`, icon: Users, color: '#88a7db' }].map(item => <WorkspaceCard key={item.title}><div className="flex items-center justify-between gap-3"><span className="text-xs text-[#97a4af]">{item.title}</span><item.icon className="h-5 w-5" style={{ color: item.color }}/></div><p className="mt-5 text-2xl font-bold">{item.value}</p><p className="mt-2 text-[11px] text-[#82909e]">{item.detail}</p></WorkspaceCard>)}</div>
    {canAnalytics&&<WorkspaceCard className="mt-5" title={ar?'اتجاه الطلبات خلال 7 أيام':'Orders over the last 7 days'} description={ar?'الطلبات الجديدة والمدفوعات اليدوية حسب يوم إنشاء الطلب بتوقيت UTC.':'New orders and paid marks by order creation date in UTC.'}>{trend.isLoading?<div className="mt-5 h-64 animate-pulse rounded-xl bg-[#303b49]/30"/>:trend.isError?<WorkspaceError error={trend.error} onRetry={()=>void trend.refetch()}/>:trend.data&&<OrdersChart data={trend.data.daily} ar={ar}/>}</WorkspaceCard>}
<div className="mt-5 grid gap-5 xl:grid-cols-[1.5fr_1fr]"><WorkspaceCard title={ar ? 'آخر الطلبات' : 'Recent orders'} description={ar ? 'طلبات حقيقية مرتبة من الأحدث.' : 'Actual orders, newest first.'}><div className="mt-5 space-y-3">{data.recentOrders.map(order => <Link key={order.id} href="/dashboard/orders" className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[#303b49] bg-[#11191f] p-4"><div><p className="text-sm font-semibold">{order.customerName}</p><p className="mt-1 text-xs text-[#97a4af]">{new Date(order.createdAt).toLocaleString(ar ? 'ar-SA' : 'en', { dateStyle: 'medium', timeStyle: 'short' })}</p></div><div className="text-end"><p className="text-sm">{order.total === null ? '—' : money(order.total, store.currency, ar)}</p><p className="mt-1 text-xs text-[#aa9bf4]">{orderStatus[order.status]?.[locale] ?? order.status}</p></div></Link>)}{!data.recentOrders.length && <div className="grid place-items-center rounded-xl border border-dashed border-[#303b49] p-8 text-center"><ShoppingBag className="mb-3 h-7 w-7 text-[#70808f]"/><p className="text-sm text-[#97a4af]">{ar ? 'تظهر الطلبات هنا عند وصولها عبر المتجر.' : 'Store orders will appear here when they arrive.'}</p></div>}</div><Link href="/dashboard/orders" className="mt-4 inline-flex items-center gap-2 text-xs text-[#aa9bf4]">{ar ? 'إدارة الطلبات' : 'Manage orders'}<ArrowUpRight className="h-4 w-4"/></Link></WorkspaceCard>
    <div className="space-y-5"><WorkspaceCard><div className="flex items-start justify-between gap-3"><div><p className="text-xs text-[#97a4af]">{ar ? 'خطة متجرك' : 'Your store plan'}</p><h2 className="mt-2 text-xl font-bold">{data.planName}</h2></div><span className="rounded-full border border-[#4b4565] bg-[#aa9bf4]/10 px-3 py-1 text-xs text-[#c8bcff]">{data.plan}</span></div><PlanUsage data={data} ar={ar}/><Link href="/dashboard/plans" className="mt-4 block text-xs text-[#aa9bf4]">{ar ? 'تفاصيل الخطط والحدود' : 'Plans and limits'}</Link></WorkspaceCard><WorkspaceCard title={ar ? 'خطوتك التالية' : 'Quick actions'}><div className="mt-4 grid gap-2">{[{ href: '/dashboard/products?new=1', label: ar ? 'أضف منتجًا إلى الكتالوج' : 'Add a product', icon: Plus }, { href: '/dashboard/telegram', label: ar ? 'صمّم تجربة البوت' : 'Design your bot', icon: MessageCircle }, { href: '/dashboard/analytics', label: ar ? 'راجع اتجاهات الطلبات' : 'View order trends', icon: Activity }].map(item => <Link key={item.href} href={item.href} className="flex items-center gap-3 rounded-xl border border-[#303b49] p-3 text-sm hover:bg-[#232b36]"><item.icon className="h-4 w-4 text-[#aa9bf4]"/>{item.label}<ArrowUpRight className="ms-auto h-4 w-4 text-[#70808f]"/></Link>)}</div></WorkspaceCard></div></div>
    <WorkspaceCard className="mt-5" title={ar ? 'تنبيهات العمل' : 'Workspace alerts'}><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[{ value: data.pendingOrders, label: ar ? 'طلبات تحتاج تجهيزًا' : 'Orders awaiting fulfillment', href: '/dashboard/orders' }, { value: data.lowStockProducts, label: ar ? 'منتجات منشورة بمخزون منخفض (3 أو أقل)' : 'Published products with low stock (3 or fewer)', href: '/dashboard/products' }, { value: data.jobs.failed ?? 0, label: ar ? 'مهام تسويق أو أتمتة فشلت' : 'Failed marketing or automation jobs', href: '/dashboard/automation' }].map(alert => <Link key={alert.href} href={alert.href} className="rounded-xl border border-[#303b49] bg-[#11191f] p-4"><strong className={`text-xl ${alert.value ? 'text-[#e0b87d]' : 'text-[#70dcb5]'}`}>{alert.value}</strong><p className="mt-2 text-xs leading-6 text-[#97a4af]">{alert.label}</p></Link>)}</div><div className="mt-4 flex flex-wrap justify-between gap-3 text-xs text-[#97a4af]"><span>{ar ? 'التصميم المنشور' : 'Published design'}: {data.telegram.published ? (ar ? 'تصميم محفوظ' : 'Saved design') : (ar ? 'القائمة الافتراضية' : 'Default menu')}</span><span>{ar ? 'آخر استقبال ناجح' : 'Last successful poll'}: {data.telegram.lastSuccessfulPollAt ? new Date(data.telegram.lastSuccessfulPollAt).toLocaleString(ar ? 'ar-SA' : 'en') : (ar ? 'لم يسجّل بعد' : 'Not recorded')}</span></div></WorkspaceCard></>}
  </div>;
}
