import { useEffect, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Link, useParams } from 'wouter';
import { ArrowLeft, ExternalLink, Package, Search, Sparkles } from 'lucide-react';
import { BrandMark } from './brand-mark';
import { teacherApi } from '../lib/teacher-api';
import './storefront.css';

type Theme = 'dark' | 'white' | 'nebula';
type Product = { id: string; categoryId: string | null; name: string; description: string; price: string; oldPrice: string | null; imageUrl: string | null; warranty: string; tags: string[]; featured: boolean; available: boolean; images: { url: string; alt: string }[] };
type Catalog = { store: { id: string; name: string; slug: string; currency: string; theme: Theme; enabled: boolean; botUrl: string | null }; categories: { id: string; name: string; description: string | null; imageUrl: string | null; emoji: string }[]; products: Product[]; page: number; hasMore: boolean };
const themes: { id: Theme; label: string; description: string }[] = [{ id: 'dark', label: 'داكن', description: 'فحمي هادئ ولمسات بنفسجية.' }, { id: 'white', label: 'أبيض', description: 'أسطح فاتحة وحدود ناعمة.' }, { id: 'nebula', label: 'LootBot Nebula', description: 'هوية كونية مع وهج وأورورا خفيفة.' }];
const money = (price: string, currency: string) => new Intl.NumberFormat('ar-SA', { style: 'currency', currency }).format(Number(price));

function ProductImage({ product }: { product: Product }) { const [failed, setFailed] = useState(false); useEffect(() => setFailed(false), [product.imageUrl]); return product.imageUrl && !failed ? <img loading="lazy" decoding="async" src={product.imageUrl} alt={product.name} onError={() => setFailed(true)}/>: <div className="sf-no-image"><Package aria-hidden="true"/><span>{failed ? 'تعذر تحميل الصورة' : 'لا توجد صورة'}</span></div>; }
export function StorefrontSurface({ data, theme, preview = false, categoryId, productId, onCategory, onProduct }: { data: Catalog; theme?: Theme; preview?: boolean; categoryId?: string; productId?: string; onCategory?: (id: string) => void; onProduct?: (id: string) => void }) {
  const [search, setSearch] = useState('');
  const active = theme ?? data.store.theme;
  const base = `/store/${encodeURIComponent(data.store.slug)}`;
  const products = data.products.filter(product => (!categoryId || product.categoryId === categoryId) && product.name.toLocaleLowerCase().includes(search.toLocaleLowerCase()));
  const product = data.products.find(item => item.id === productId);
  return <div dir="rtl" className={`storefront sf-${active} ${preview ? 'sf-preview' : ''}`}>
    <header className="sf-top"><div className="sf-wordmark"><BrandMark/><span><strong>{data.store.name}</strong><small>LootBot</small></span></div>{data.store.botUrl && <a className="sf-link" href={data.store.botUrl} target="_blank" rel="noopener noreferrer">بوت المتجر <ExternalLink size={15}/></a>}</header>
    {!productId && <section className="sf-hero"><div className="sf-orbit" aria-hidden="true"/><div className="sf-hero-content"><p className="sf-eyebrow"><Sparkles size={14}/>{active === 'nebula' ? 'LOOTBOT NEBULA' : 'كتالوج المتجر'}</p><h1>{data.store.name}</h1><p>استكشف المنتجات المنشورة، واختر ما يناسبك.</p>{data.store.botUrl ? <a className="sf-cta" href={data.store.botUrl} target="_blank" rel="noopener noreferrer">استعرض المتجر في تيليجرام <ArrowLeft size={17}/></a> : <p className="sf-muted">بوت المتجر غير متاح حاليًا.</p>}</div></section>}
    <main className="sf-main">
      {productId ? product ? <><div className="sf-breadcrumb"><Link href={base}>المنتجات</Link><span>/</span>{product.categoryId && <Link href={`${base}/categories/${encodeURIComponent(product.categoryId)}`}>{data.categories.find(category => category.id === product.categoryId)?.name || 'التصنيف'}</Link>}<span>/</span>{product.name}</div><article className="sf-detail"><div className="sf-detail-image"><ProductImage product={product}/><div className="sf-gallery">{product.images.map((image, index) => <img key={`${image.url}-${index}`} src={image.url} alt={image.alt || `${product.name} — صورة ${index + 1}`} loading="lazy"/>)}</div></div><div><h1>{product.name}</h1><p className="sf-detail-price">{money(product.price, data.store.currency)} {product.oldPrice && Number(product.oldPrice) > Number(product.price) && <del>{money(product.oldPrice, data.store.currency)}</del>}</p><p className="sf-description">{product.description || 'لا يوجد وصف إضافي لهذا المنتج.'}</p>{product.warranty && <p className="sf-muted">الضمان: {product.warranty}</p>}<p className="sf-status">{product.available ? 'متوفر' : 'غير متوفر حاليًا'}</p>{data.store.botUrl && <a className="sf-cta" href={data.store.botUrl} target="_blank" rel="noopener noreferrer">تفاصيل الطلب عبر البوت <ExternalLink size={16}/></a>}<div className="sf-tags">{product.tags.map(tag => <span key={tag}>{tag}</span>)}</div></div></article></> : <p>المنتج غير متاح.</p> : <>
        <div className="sf-toolbar"><nav aria-label="تصنيفات المتجر" className="sf-categories">{[{ id: '', name: 'كل المنتجات' }, ...data.categories].map(category => preview ? <button type="button" aria-pressed={categoryId === category.id || !categoryId && !category.id} key={category.id} onClick={() => onCategory?.(category.id)}>{category.name}</button> : <Link key={category.id} aria-current={categoryId === category.id || !categoryId && !category.id ? 'page' : undefined} href={category.id ? `${base}/categories/${encodeURIComponent(category.id)}` : base}>{category.name}</Link>)}</nav><label className="sf-search"><Search size={16}/><input aria-label="البحث في المنتجات الظاهرة" value={search} onChange={event => setSearch(event.target.value)} placeholder="ابحث في هذه الصفحة…"/></label></div>
        {categoryId && <h2 className="sf-category-title">{data.categories.find(category => category.id === categoryId)?.name || 'منتجات التصنيف'}</h2>}
        <div className="sf-grid">{products.map(product => <article key={product.id} className="sf-product"><div className="sf-product-image"><ProductImage product={product}/>{product.featured && <span className="sf-featured">مختار</span>}</div><div className="sf-product-info"><p className="sf-muted">{data.categories.find(category => category.id === product.categoryId)?.name || 'الكتالوج'}</p><h2>{product.name}</h2><div className="sf-price">{money(product.price, data.store.currency)}{product.oldPrice && Number(product.oldPrice) > Number(product.price) && <del>{money(product.oldPrice, data.store.currency)}</del>}</div><p className="sf-status">{product.available ? 'متوفر' : 'غير متوفر حاليًا'}</p>{preview ? <button className="sf-card-cta" onClick={() => onProduct?.(product.id)}>عرض التفاصيل <ArrowLeft size={16}/></button> : <Link className="sf-card-cta" href={`${base}/products/${encodeURIComponent(product.id)}`}>عرض التفاصيل <ArrowLeft size={16}/></Link>}</div></article>)}</div>
        {!products.length && <p className="sf-empty">لا توجد منتجات منشورة تطابق هذا الاختيار.</p>}
      </>}
    </main><footer className="sf-footer"><BrandMark small/><span>مدعوم بواسطة LootBot</span>{preview && <span>معاينة بالمنتجات المنشورة الفعلية</span>}</footer>
  </div>;
}

export function PublicStorefront() {
  const { slug = '', categoryId, productId } = useParams();
  const [page, setPage] = useState(1);
  useEffect(() => { setPage(1); }, [slug, categoryId]);
  const path = `/storefront/${encodeURIComponent(slug)}${productId ? `/products/${encodeURIComponent(productId)}` : `?page=${page}${categoryId ? `&category=${encodeURIComponent(categoryId)}` : ''}`}`;
  const query = useQuery({ queryKey: ['storefront', slug, categoryId, productId, page], queryFn: () => teacherApi<Catalog>(path), retry: 1 });
  if (query.isLoading) return <div className="storefront sf-dark sf-state" role="status"><BrandMark/><p>جار تحميل المتجر…</p></div>;
  if (query.isError || !query.data) return <div dir="rtl" className="storefront sf-dark sf-state"><BrandMark/><h1>تعذر فتح المتجر</h1><p role="alert">{query.error instanceof Error ? query.error.message : 'حاول مجددًا.'}</p><button className="sf-cta" onClick={() => void query.refetch()}>إعادة المحاولة</button><Link href="/">الرئيسية</Link></div>;
  return <><StorefrontSurface data={query.data} categoryId={categoryId} productId={productId}/>{!productId && <nav className={`storefront sf-${query.data.store.theme} sf-paging`} aria-label="صفحات المنتجات"><button className="sf-card-cta" disabled={page <= 1} onClick={() => setPage(value => value - 1)}>السابق</button><span>الصفحة {page}</span><button className="sf-card-cta" disabled={!query.data.hasMore} onClick={() => setPage(value => value + 1)}>التالي</button></nav>}</>;
}

export function StoreAppearance({ store }: { store?: { id: string; slug: string } }) {
  const id = store?.id ?? '', [draft, setDraft] = useState<{ theme: Theme; enabled: boolean }>({ theme: 'dark', enabled: false });
  const [pending, setPending] = useState(false), [notice, setNotice] = useState(''), [error, setError] = useState(''), [category, setCategory] = useState(''), [product, setProduct] = useState('');
  const query = useQuery({ queryKey: ['store-appearance', id], enabled: !!id, queryFn: () => teacherApi<typeof draft>(`/stores/${encodeURIComponent(id)}/storefront`) });
  const preview = useQuery({ queryKey: ['storefront-preview', id], enabled: !!id, queryFn: () => teacherApi<Catalog>(`/stores/${encodeURIComponent(id)}/storefront/preview`) });
  useEffect(() => { setNotice(''); setError(''); setCategory(''); setProduct(''); if (query.data) setDraft(query.data); }, [query.data, id]);
  async function save() { if (draft.enabled && !query.data?.enabled && !window.confirm('تفعيل الرابط العام يعرض المنتجات المنشورة في الكتالوج للجميع. هل تريد المتابعة؟')) return; setPending(true); setError(''); setNotice(''); try { await teacherApi(`/stores/${encodeURIComponent(id)}/storefront`, 'PATCH', draft); await query.refetch(); await preview.refetch(); setNotice('تم حفظ المظهر. المنتجات والطلبات لم تتغير.'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'تعذر الحفظ.'); } finally { setPending(false); } }
  if (!id) return null;
  return <section className="glass-panel mt-6 space-y-5" dir="rtl"><header><h2 className="text-xl font-semibold">مظهر واجهة المتجر</h2><p className="glass-muted mt-2 text-sm leading-6">المظهر محفوظ لكل متجر، ويُطبّق على الكتالوج والتصنيفات وتفاصيل المنتجات.</p></header>{query.isLoading ? <p role="status">جار تحميل المظهر…</p> : query.isError ? <button onClick={() => void query.refetch()}>تعذر التحميل — إعادة المحاولة</button> : <><fieldset disabled={pending} className="grid gap-3 sm:grid-cols-3"><legend className="sr-only">اختر المظهر</legend>{themes.map(theme => <label className={`sf-theme-choice choice-${theme.id} ${draft.theme === theme.id ? 'selected' : ''}`} key={theme.id}><input type="radio" name={`theme-${id}`} checked={draft.theme === theme.id} onChange={() => setDraft({ ...draft, theme: theme.id })}/><span><strong>{theme.label}</strong><small>{theme.description}</small></span></label>)}</fieldset><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={draft.enabled} onChange={event => setDraft({ ...draft, enabled: event.target.checked })}/>تفعيل رابط الكتالوج العام (المنتجات المنشورة فقط)</label><div className="flex flex-wrap gap-3"><button className="brand-action rounded-xl px-5 py-3 text-sm font-semibold" onClick={() => void save()} disabled={pending}>{pending ? 'جار الحفظ…' : 'حفظ المظهر'}</button>{query.data?.enabled && <Link className="rounded-xl border border-[#414960] px-5 py-3 text-sm" href={`/store/${encodeURIComponent(store!.slug)}`} target="_blank">فتح واجهة المتجر <ExternalLink className="inline" size={14}/></Link>}</div></>}{notice && <p role="status" className="text-sm text-[#c6bcff]">{notice}</p>}{error && <p role="alert" className="glass-error">{error}</p>}<details open><summary className="cursor-pointer text-sm font-semibold">معاينة تفاعلية</summary><div className="mt-4 overflow-hidden rounded-2xl border border-[#414960]">{preview.isLoading ? <p className="p-5" role="status">جار تحميل المنتجات…</p> : preview.isError ? <button className="p-5" onClick={() => void preview.refetch()}>تعذر تحميل المعاينة — أعد المحاولة</button> : preview.data && <>{product && <button className="w-full bg-[#252c40] p-3 text-sm" onClick={() => setProduct('')}>العودة إلى قائمة المنتجات</button>}<StorefrontSurface data={preview.data} theme={draft.theme} preview categoryId={category} productId={product} onCategory={setCategory} onProduct={setProduct}/></>}</div></details></section>;
}
