import { useEffect, useState, type FormEvent } from 'react';
import { useQuery } from '@tanstack/react-query';
import { useGetCsrfToken } from '@workspace/api-client-react';
import { ShieldCheck, UserPlus } from 'lucide-react';
import { LockedWorkspace, WorkspaceCard, WorkspaceError, WorkspaceHeading, WorkspaceSkeleton, workspaceButton, workspaceInput, workspaceRequest } from './workspace-ui';

type Member = { id: string; userId: string; name: string; email: string; permissions: string[]; enabled: boolean; createdAt: string };
type Team = { enabled: boolean; members: Member[]; labels: Record<string, string> };
const enLabels: Record<string, string> = { 'overview.read': 'View overview', 'catalog.read': 'View catalog', 'catalog.write': 'Manage catalog', 'orders.read': 'View orders', 'orders.manage': 'Manage fulfillment', 'customers.read': 'View customers', 'customers.manage': 'Manage customer segments', 'telegram.design': 'Design and publish bot', 'marketing.manage': 'Manage and send campaigns', 'automation.manage': 'Manage automation and journeys', 'analytics.read': 'View nonfinancial analytics' };
export function TeamWorkspace({ store, locale = 'ar' }: { store?: { id: string; name: string }; locale?: 'ar' | 'en' }) {
  const ar = locale === 'ar'; const storeId = store?.id ?? ''; const csrf = useGetCsrfToken();
  const [selected, setSelected] = useState<Member | null>(null); const [email, setEmail] = useState(''); const [permissions, setPermissions] = useState<string[]>(['overview.read', 'catalog.read', 'orders.read']);
  const [pending, setPending] = useState(false); const [notice, setNotice] = useState(''); const [error, setError] = useState('');
  useEffect(() => { setSelected(null); setEmail(''); setNotice(''); setError(''); }, [storeId]);
  const team = useQuery({ queryKey: ['team', storeId], enabled: !!storeId, queryFn: () => workspaceRequest<Team>(`/api/stores/${encodeURIComponent(storeId)}/team`) });
  const send = async (path: string, method: string, body: unknown) => {
    if (!csrf.data?.token || pending) return; setPending(true); setNotice(''); setError('');
    try { const response = await fetch(`/api/stores/${encodeURIComponent(storeId)}/team${path}`, { method, credentials: 'include', headers: { 'content-type': 'application/json', 'x-csrf-token': csrf.data.token }, body: JSON.stringify(body) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? 'Request failed'); await team.refetch(); setSelected(null); setEmail(''); setNotice(ar ? 'حُفظت صلاحيات الفريق.' : 'Team access saved.'); }
    catch (cause) { setError(cause instanceof Error ? cause.message : 'Request failed'); } finally { setPending(false); }
  };
  const submit = (event: FormEvent) => { event.preventDefault(); void send(selected ? `/${selected.id}` : '', selected ? 'PATCH' : 'POST', selected ? { permissions, enabled: true } : { email, permissions }); };
  if (!store) return <p>{ar ? 'اختر متجرًا أولًا.' : 'Choose a store first.'}</p>;
  return <div className="fade-up"><WorkspaceHeading eyebrow={store.name} title={ar ? 'الفريق والصلاحيات' : 'Team and permissions'} description={ar ? 'امنح كل عضو نطاق عمل واضحًا في هذا المتجر. تبقى إدارة الفريق والدفعات وأمان الاتصال بيد المالك.' : 'Give each member a clear scope in this store. Team access, payments and connection security remain with the owner.'}/>
    {team.isLoading ? <WorkspaceSkeleton/> : team.isError ? <WorkspaceError error={team.error} onRetry={() => void team.refetch()}/> : !team.data?.enabled ? <LockedWorkspace ar={ar} title={ar ? 'فريق متجرك على Business' : 'Your team on Business'} description={ar ? 'أضف مستخدمين لديهم حسابات حالية، وحدد صلاحياتهم لكل متجر. تراجع حدود الخطة في كل طلب.' : 'Add existing account holders with permissions scoped to this store. Plan access is checked on every request.'}/> : <div className="grid gap-5 xl:grid-cols-[1fr_1.2fr]">
      <WorkspaceCard title={selected ? (ar ? `صلاحيات ${selected.name}` : `${selected.name} permissions`) : (ar ? 'إضافة عضو' : 'Add a member')} description={ar ? 'يجب أن يسجّل العضو حسابًا أولًا بالبريد الذي تكتبه هنا.' : 'The member must first register an account using this email.'}><form onSubmit={submit} className="mt-5 space-y-4"><label className="block text-sm">{ar ? 'البريد الإلكتروني للحساب' : 'Account email'}<input className={`${workspaceInput} mt-2`} type="email" autoComplete="off" value={selected?.email ?? email} onChange={event => setEmail(event.target.value)} required disabled={!!selected} maxLength={254}/></label><fieldset><legend className="mb-3 text-sm font-semibold">{ar ? 'الصلاحيات المسموحة' : 'Allowed permissions'}</legend><div className="grid gap-2 sm:grid-cols-2">{Object.keys(team.data.labels).map(permission => <label key={permission} className="flex items-start gap-3 rounded-xl border border-[#303b49] p-3 text-xs leading-6"><input type="checkbox" className="mt-1 accent-[#aa9bf4]" checked={permissions.includes(permission)} onChange={event => setPermissions(current => event.target.checked ? [...current, permission] : current.filter(value => value !== permission))}/>{ar ? team.data!.labels[permission] : enLabels[permission] ?? permission}</label>)}</div></fieldset><p className="flex gap-2 rounded-xl bg-[#11191f] p-3 text-xs leading-6 text-[#97a4af]"><ShieldCheck className="mt-1 h-4 w-4 shrink-0 text-[#70dcb5]"/>{ar ? 'صلاحيات التعديل تتضمن القراءة. لا تمنح العضوية أي صلاحية Super Admin أو وصول إلى متجر آخر. تعطيل العضو يسحب وصوله فورًا.' : 'Write access includes reading. Membership never grants Super Admin access or another store. Disabling a member revokes access immediately.'}</p><div className="flex flex-wrap gap-2"><button disabled={!csrf.data?.token || pending || !permissions.length} className={`${workspaceButton} bg-[#aa9bf4] text-[#161329]`}><UserPlus className="h-4 w-4"/>{ar ? 'حفظ الصلاحيات' : 'Save access'}</button>{selected && <button type="button" className={workspaceButton} onClick={() => { setSelected(null); setEmail(''); }}>{ar ? 'إلغاء التعديل' : 'Cancel edit'}</button>}</div></form></WorkspaceCard>
      <WorkspaceCard title={ar ? 'أعضاء الفريق' : 'Team members'}><div className="mt-5 space-y-3">{team.data.members.map(member => <article key={member.id} className="rounded-xl border border-[#303b49] bg-[#11191f] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><p className="font-semibold">{member.name}</p><p className="mt-1 break-all text-xs text-[#97a4af]">{member.email}</p></div><span className={`rounded-full px-3 py-1 text-xs ${member.enabled ? 'bg-[#203a30] text-[#70dcb5]' : 'bg-[#352a24] text-[#e0b87d]'}`}>{member.enabled ? (ar ? 'فعال' : 'Active') : (ar ? 'معطل' : 'Disabled')}</span></div><div className="mt-3 flex flex-wrap gap-2">{member.permissions.map(permission => <span key={permission} className="rounded-md bg-[#232b36] px-2 py-1 text-[10px] text-[#b0bac8]">{ar ? team.data!.labels[permission] : enLabels[permission] ?? permission}</span>)}</div><div className="mt-4 flex gap-2"><button className={workspaceButton} onClick={() => { setSelected(member); setPermissions(member.permissions); }}>{ar ? 'تعديل' : 'Edit'}</button><button className={`${workspaceButton} ${member.enabled ? 'text-[#e4a09a]' : 'text-[#70dcb5]'}`} disabled={pending || !csrf.data?.token} onClick={() => void send(`/${member.id}`, 'PATCH', { enabled: !member.enabled })}>{member.enabled ? (ar ? 'سحب الوصول' : 'Revoke access') : (ar ? 'إعادة التفعيل' : 'Enable access')}</button></div></article>)}{!team.data.members.length && <p className="rounded-xl border border-dashed border-[#303b49] p-6 text-sm text-[#97a4af]">{ar ? 'أنت تدير المتجر بمفردك حاليًا.' : 'You currently manage this store on your own.'}</p>}</div></WorkspaceCard>
    </div>}{team.data?.enabled===false&&team.data.members.length>0&&<WorkspaceCard className="mt-5" title={ar?'الوصول السابق للفريق':'Previous team access'} description={ar?'تمنع الخطة الحالية وصول الفريق تلقائيًا. يمكنك سحب العضوية نهائيًا قبل إعادة الترقية.':'The current plan blocks staff access automatically. You can permanently revoke memberships before upgrading again.'}><div className="mt-4 space-y-3">{team.data.members.map(member=><div key={member.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[#303b49] p-3"><p className="text-sm">{member.name}<span className="ms-2 text-xs text-[#97a4af]">{member.email}</span></p><button disabled={!member.enabled||pending||!csrf.data?.token} onClick={()=>void send(`/${member.id}`,'PATCH',{enabled:false})} className={`${workspaceButton} text-[#e4a09a]`}>{ar?'سحب العضوية':'Revoke membership'}</button></div>)}</div></WorkspaceCard>}{notice && <p role="status" className="mt-4 rounded-xl bg-[#203a30] p-4 text-sm text-[#70dcb5]">{notice}</p>}{error && <WorkspaceError error={error} onRetry={() => setError('')}/>}</div>;
}
