import { useEffect, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { TelegramScreenStyleEditor, themes, type ScreenStyle } from './telegram-screen-style-editor';
import { StudioTargetPicker } from './studio-target-picker';

type Configuration = { layout?:string; productCardStyle?:string; announcement?:string; customerGreeting?:boolean; version: 1; welcomeMessage: string; headerTitle?: string; headerSubtitle?: string; footer?: string; theme?: string; bannerUrl?: string; screenStyles?: Record<string, ScreenStyle>; columns: 1 | 2 | 3; showEmoji: boolean; buttons: { action: string; title: string; emoji: string; enabled: boolean }[] };
type Preview = { text: string; imageUrl?: string; images?: string[]; keyboard: { text: string; callback_data?: string; url?: string; previewDisabled?: boolean }[][] };
type Studio = { enabled: boolean; draft: Configuration; published: Configuration | null; revision: number; preview: Preview };
const optionalActions = { offers: { title: 'العروض', emoji: '🔥' }, cart: { title: 'السلة', emoji: '🛒' }, favorites: { title: 'المفضلة', emoji: '❤️' }, points: { title: 'النقاط', emoji: '⭐' }, referrals: { title: 'الإحالات', emoji: '🎁' }, coupons: { title: 'الكوبونات', emoji: '🎫' }, support: { title: 'الدعم', emoji: '💬' }, notifications: { title: 'الإشعارات', emoji: '🔔' } };
export function TelegramHomeStudio({ storeId, csrfToken, locale }: { storeId: string; csrfToken?: string; locale: 'ar' | 'en' }) {
  const ar = locale === 'ar'; const qc = useQueryClient();
  const [draft, setDraft] = useState<Configuration | null>(null); const [preview, setPreview] = useState<Preview | null>(null);
  const [dirty, setDirty] = useState(false); const [pending, setPending] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const [customerId, setCustomerId] = useState(''); const [search, setSearch] = useState('');
  const [previewState, setPreviewState] = useState('');
  const query = useQuery({ queryKey: ['telegram-home-studio', storeId], enabled: !!storeId, refetchOnWindowFocus: false, queryFn: async () => {
    const response = await fetch(`/api/stores/${encodeURIComponent(storeId)}/telegram/studio`, { credentials: 'include' });
    if (!response.ok) throw new Error('Could not load studio'); return response.json() as Promise<Studio>;
  }});
  useEffect(() => { if (query.data) { setDraft(query.data.draft); setPreview(query.data.preview); setDirty(false); } }, [query.data]);
  const change = (next: Configuration) => { setDraft(next); setDirty(true); setNotice(''); setPreview(null); };
  const submit = async (action: 'draft' | 'preview' | 'publish', callbackData = 'lb:home', state = previewState) => {
    if (!draft || !csrfToken || pending) return;
    setPending(action); setError(''); setNotice('');
    try {
      const response = await fetch(`/api/stores/${encodeURIComponent(storeId)}/telegram/studio/${action}`, {
        method: 'POST', credentials: 'include', headers: { 'content-type': 'application/json', 'x-csrf-token': csrfToken },
        body: JSON.stringify({ configuration: draft, revision: query.data?.revision, callbackData, customerId: customerId || undefined, search, ...(action === 'preview' && state ? { state } : {}) }),
      });
      const payload = await response.json(); if (!response.ok) throw new Error(payload.error || (ar ? 'تعذر إكمال الطلب.' : 'Request failed.'));
      setPreview(payload.preview);
      if (action === 'preview') setPreviewState(state);
      if (action !== 'preview') { qc.setQueryData(['telegram-home-studio', storeId], payload); setDirty(false); }
      setNotice(action === 'publish' ? (ar ? 'تم النشر. يظهر التصميم عند /start أو العودة للرئيسية.' : 'Published. Appears on /start or Home.') : action === 'draft' ? (ar ? 'حُفظت المسودة. اضغط نشر لتطبيقها على Telegram.' : 'Draft saved. Publish to apply it to Telegram.') : '');
    } catch (cause) { setError(cause instanceof Error ? cause.message : 'Request failed'); }
    finally { setPending(''); }
  };
  const reorder = (index: number, direction: number) => {
    if (!draft || index + direction < 0 || index + direction >= draft.buttons.length) return;
    const buttons = [...draft.buttons]; [buttons[index], buttons[index + direction]] = [buttons[index + direction], buttons[index]]; change({ ...draft, buttons });
  };
  if (!storeId) return null;
  return <section className="mt-5 rounded-2xl border border-[#293638] bg-[#171f22] p-5 md:p-7">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">{ar ? 'مصمم الصفحة الرئيسية للبوت' : 'Bot home designer'}</h2><p className="mt-2 text-xs text-[#879595]">{ar ? 'مسودة مستقلة، معاينة من الخادم، ثم نشر إلى Telegram.' : 'Save a draft, preview it, then publish to Telegram.'}</p></div><span className="rounded-full bg-[#1b3029] px-3 py-1 text-xs text-[#85dabc]">Pro · Business</span></div>
    {query.isLoading ? <p className="mt-4">{ar ? 'جار التحميل…' : 'Loading…'}</p> : query.isError ? <button onClick={() => void query.refetch()} className="mt-4 text-[#e4a09a]">{ar ? 'تعذر التحميل. إعادة المحاولة' : 'Could not load. Retry'}</button> : !query.data?.enabled ? <p className="mt-4 text-sm text-[#e5c996]">{ar ? 'التخصيص متاح في Pro وBusiness. القائمة الأساسية تعمل لجميع المتاجر.' : 'Customization requires Pro or Business. The basic menu works for all stores.'}</p> : draft && <>
      <div className="mt-5 grid gap-5 lg:grid-cols-2">
        <fieldset disabled={!!pending} className="space-y-4 disabled:opacity-60">
          <details open className="rounded-xl border border-[#354344] p-4"><summary className="cursor-pointer font-semibold">{ar ? "التخطيط" : "Layout"}</summary><div className="mt-4 space-y-4"><label className="block text-sm">{ar?'تخطيط الرئيسية':'Home layout'}<select className="mt-2 w-full rounded-xl border border-[#354344] bg-[#182123] p-3" value={draft.layout??'custom-order'} onChange={e=>change({...draft,layout:e.target.value})}>{['grid-2','grid-3','vertical','compact','sections','featured-first','categories-first','offers-first','custom-order'].map(v=><option key={v} value={v}>{ar?{'grid-2':'شبكة عمودين','grid-3':'شبكة ثلاثة أعمدة',vertical:'قائمة عمودية',compact:'قائمة مختصرة',sections:'أقسام','featured-first':'المميز أولًا','categories-first':'التصنيفات أولًا','offers-first':'العروض أولًا','custom-order':'ترتيب مخصص'}[v]:v}</option>)}</select></label><div className="flex flex-wrap gap-4"><label className="text-sm">{ar ? 'أعمدة القائمة' : 'Menu columns'}<select value={draft.columns} onChange={e => change({ ...draft, columns: Number(e.target.value) as 1 | 2 | 3 })} className="ms-2 rounded-lg border border-[#354344] bg-[#182123] p-2"><option value={1}>1</option><option value={2}>2</option><option value={3}>3</option></select></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={draft.showEmoji} onChange={e => change({ ...draft, showEmoji: e.target.checked })}/>{ar ? 'إظهار الرموز' : 'Show emoji'}</label></div>
          </div></details><details className="rounded-xl border border-[#354344] p-4"><summary className="cursor-pointer font-semibold">{ar ? "المحتوى" : "Content"}</summary><div className="mt-4 space-y-4"><label className="block text-sm">{ar ? 'عنوان المتجر في البوت' : 'Bot header title'}<input maxLength={100} value={draft.headerTitle ?? ''} onChange={e => change({ ...draft, headerTitle: e.target.value })} className="mt-2 w-full rounded-xl border border-[#354344] bg-[#182123] p-3"/></label>
          <label className="block text-sm">{ar ? 'وصف مختصر' : 'Header subtitle'}<input maxLength={200} value={draft.headerSubtitle ?? ''} onChange={e => change({ ...draft, headerSubtitle: e.target.value })} className="mt-2 w-full rounded-xl border border-[#354344] bg-[#182123] p-3"/></label>
          <label className="block text-sm">{ar ? 'رسالة الترحيب' : 'Welcome message'}<textarea rows={4} maxLength={800} value={draft.welcomeMessage} onChange={e => change({ ...draft, welcomeMessage: e.target.value })} className="mt-2 w-full rounded-xl border border-[#354344] bg-[#182123] p-3"/><span className="text-xs text-[#879595]">{'{{store}} · {{customer}}'}</span></label>
          <label className="block text-sm">{ar ? 'تذييل الرسالة' : 'Message footer'}<input maxLength={200} value={draft.footer ?? ''} onChange={e => change({ ...draft, footer: e.target.value })} className="mt-2 w-full rounded-xl border border-[#354344] bg-[#182123] p-3"/></label>
          <label className="block text-sm">{ar?'إعلان المتجر':'Store announcement'}<textarea className="mt-2 w-full rounded-xl border border-[#354344] bg-[#182123] p-3" maxLength={500} value={draft.announcement??''} onChange={e=>change({...draft,announcement:e.target.value})}/></label><label className="flex gap-2 text-sm"><input type="checkbox" checked={draft.customerGreeting??true} onChange={e=>change({...draft,customerGreeting:e.target.checked})}/>{ar?'تخصيص الترحيب باسم العميل':'Personalize customer greeting'}</label></div></details><details className="rounded-xl border border-[#354344] p-4"><summary className="cursor-pointer font-semibold">{ar ? "القائمة والتنقل" : "Navigation"}</summary><div className="mt-4 space-y-4"><div className="space-y-3">{draft.buttons.map((button, index) => <div key={button.action} className="rounded-xl border border-[#354344] p-3">
            <div className="flex gap-2"><input aria-label={ar ? 'رمز الزر' : 'Button emoji'} value={button.emoji} maxLength={16} onChange={e => change({ ...draft, buttons: draft.buttons.map((item, i) => i === index ? { ...item, emoji: e.target.value } : item) })} className="w-14 rounded-lg border border-[#354344] bg-[#182123] p-2"/><input aria-label={ar ? 'عنوان الزر' : 'Button title'} value={button.title} maxLength={40} onChange={e => change({ ...draft, buttons: draft.buttons.map((item, i) => i === index ? { ...item, title: e.target.value } : item) })} className="min-w-0 flex-1 rounded-lg border border-[#354344] bg-[#182123] p-2"/></div>
            <div className="mt-2 flex items-center gap-3 text-xs"><label className="me-auto"><input type="checkbox" checked={button.enabled} onChange={e => change({ ...draft, buttons: draft.buttons.map((item, i) => i === index ? { ...item, enabled: e.target.checked } : item) })}/> {ar ? 'ظاهر' : 'Visible'}</label><button type="button" disabled={index === 0} onClick={() => reorder(index, -1)} className="disabled:opacity-40">↑</button><button type="button" disabled={index === draft.buttons.length - 1} onClick={() => reorder(index, 1)} className="disabled:opacity-40">↓</button>{button.action in optionalActions && <button type="button" className="text-[#e4a09a]" onClick={() => change({ ...draft, buttons: draft.buttons.filter((_, i) => i !== index) })}>{ar ? "حذف" : "Remove"}</button>}</div>
          </div>)}</div>
        <label className="mt-4 block text-sm">{ar ? 'إضافة زر اختياري' : 'Add an optional button'}<select value="" onChange={e => { const action = e.target.value as keyof typeof optionalActions; if (!action) return; const item = optionalActions[action]; change({ ...draft, buttons: [...draft.buttons, { action, ...item, enabled: true }] }); }} className="mt-2 w-full rounded-xl border border-[#354344] bg-[#182123] p-3"><option value="">{ar ? 'اختر زرًا لإضافته' : 'Choose a button to add'}</option>{Object.entries(optionalActions).filter(([action]) => !draft.buttons.some(b => b.action === action)).map(([action, item]) => <option key={action} value={action}>{ar ? item.title : action}</option>)}</select></label><p className="mt-3 text-xs leading-6 text-[#879595]">{ar ? 'الأزرار المرتبطة بميزة غير متاحة في الخطة أو غير مفعلة في المتجر تُخفى في البوت. تعطيل زر صراحةً يُبقيه مخفيًا.' : 'Buttons for unavailable or disabled store features are hidden in the bot. Explicitly disabled buttons stay hidden.'}</p></div></details><details className="rounded-xl border border-[#354344] p-4"><summary className="cursor-pointer font-semibold">{ar ? "المظهر والشاشات" : "Appearance"}</summary><div className="mt-4 space-y-4"><label className="block text-sm">{ar?'أسلوب بطاقة المنتج':'Product card style'}<select className="mt-2 w-full rounded-xl border border-[#354344] bg-[#182123] p-3" value={draft.productCardStyle??'classic'} onChange={e=>change({...draft,productCardStyle:e.target.value})}>{['classic','compact','premium','sale','minimal','image-first','price-first','warranty-first','VIP'].map(v=><option key={v}>{v}</option>)}</select></label><label className="block text-sm">{ar ? 'الثيم' : 'Theme'}<select className="mt-2 w-full rounded-xl border border-[#354344] bg-[#182123] p-3" value={draft.theme ?? ''} onChange={e => change({ ...draft, theme: e.target.value || undefined })}><option value="">{ar ? 'الافتراضي' : 'Default'}</option>{themes.map(theme => <option key={theme}>{theme}</option>)}</select></label>
          <label className="block text-sm">{ar ? 'رابط بانر الرئيسية' : 'Home banner URL'}<input type="url" maxLength={1500} value={draft.bannerUrl ?? ''} onChange={e => change({ ...draft, bannerUrl: e.target.value })} className="mt-2 w-full rounded-xl border border-[#354344] bg-[#182123] p-3"/></label>
          <TelegramScreenStyleEditor ar={ar} value={draft.screenStyles ?? {}} onChange={screenStyles => change({ ...draft, screenStyles })}/>
          </div></details></fieldset>
        <div className="rounded-2xl border border-[#354344] bg-[#10191c] p-4"><h3 className="text-sm text-[#879595]">{ar ? 'معاينة Telegram' : 'Telegram preview'}</h3><label className="mt-3 block text-xs">{ar ? "حالة المعاينة" : "Preview state"}<select className="mt-2 w-full rounded-lg bg-[#182123] p-2" value={previewState} onChange={e => { setPreviewState(e.target.value); setPreview(null); }}><option value="">{ar ? "تنقل في المتجر" : "Browse the store"}</option><option value="empty">{ar ? "حالة فارغة" : "Empty state"}</option><option value="error">{ar ? "حالة خطأ" : "Error state"}</option><option value="success">{ar ? "حالة نجاح" : "Success state"}</option></select></label><StudioTargetPicker storeId={storeId} kind="customers" value={customerId} ar={ar} label={ar ? 'حساب العميل في المعاينة' : 'Preview customer'} placeholder={ar ? 'زائر عام' : 'Guest'} onChange={value => { setCustomerId(value); setPreview(null); }}/><label className="mt-3 block text-xs">{ar ? 'عبارة البحث' : 'Search phrase'}<input maxLength={120} className="mt-2 w-full rounded-lg bg-[#182123] p-2" value={search} onChange={e => setSearch(e.target.value)}/></label><p className="mt-3 text-xs text-[#879595]">{ar ? 'اضغط الأزرار لاستعراض الشاشات والبيانات. الشراء لا ينفّذ في المعاينة.' : 'Click buttons to browse screens and data. Preview never places orders.'}</p>{preview ? <>{Array.from(new Set(preview.images?.length ? preview.images : preview.imageUrl ? [preview.imageUrl] : [])).map((imageUrl, index) => <img key={imageUrl} src={imageUrl} alt={ar ? `صورة شاشة البوت ${index + 1}` : `Bot screen image ${index + 1}`} className="mt-4 max-h-64 w-full rounded-xl object-contain"/>)}<p className="mt-4 whitespace-pre-wrap rounded-xl bg-[#21332f] p-4 text-sm">{preview.text}</p><div className="mt-3 space-y-2">{preview.keyboard.map((row, index) => <div key={index} className="flex gap-2">{row.map(button => <button type="button" disabled={!!pending || button.previewDisabled || !button.callback_data || button.callback_data.startsWith("lb:buy:") || button.callback_data === "lb:close"} onClick={() => void submit("preview", button.callback_data, "")} key={button.callback_data ?? button.url ?? button.text} className="min-w-0 flex-1 rounded-lg border border-[#365749] bg-[#1b3029] p-2 text-center text-xs disabled:opacity-40">{button.text}</button>)}</div>)}</div></> : <p className="mt-5 text-sm text-[#879595]">{ar ? 'اضغط معاينة لعرض التعديلات.' : 'Preview to render your changes.'}</p>}<p className="mt-5 text-xs text-[#879595]">{query.data.published ? (ar ? 'يوجد تصميم منشور.' : 'A design is published.') : (ar ? 'Telegram يستخدم القائمة الافتراضية حتى النشر.' : 'Telegram uses the default menu until published.')}</p></div>
      </div>
      <div className="mt-5 flex flex-wrap gap-3"><button type="button" className="rounded-xl border border-[#354344] px-4 py-2 text-sm" onClick={()=>{if(draft)change({...draft,layout:"grid-2",productCardStyle:"classic",theme:undefined,screenStyles:{},bannerUrl:"",announcement:"",customerGreeting:true})}}>{ar?"إعادة ضبط المظهر":"Reset appearance"}</button><button disabled={!csrfToken || !!pending} onClick={() => void submit('draft')} className="rounded-xl border border-[#354344] px-4 py-2 text-sm disabled:opacity-40">{ar ? 'حفظ المسودة' : 'Save draft'}</button><button disabled={!csrfToken || !!pending} onClick={() => void submit('preview')} className="rounded-xl border border-[#354344] px-4 py-2 text-sm disabled:opacity-40">{ar ? 'معاينة' : 'Preview'}</button><button disabled={!csrfToken || !!pending || dirty} onClick={() => void submit('publish')} className="rounded-xl bg-[#62d6aa] px-4 py-2 text-sm font-bold text-[#10231d] disabled:opacity-40">{ar ? 'نشر إلى Telegram' : 'Publish to Telegram'}</button>{dirty && <span className="self-center text-xs text-[#e5c996]">{ar ? 'احفظ المسودة قبل النشر.' : 'Save before publishing.'}</span>}</div>
    </>}
    {error && <p role="alert" className="mt-3 text-sm text-[#e4a09a]">{error}</p>}{notice && <p role="status" className="mt-3 text-sm text-[#80d7b5]">{notice}</p>}
  </section>;
}
