export const themes = ['Gaming','Neon','Premium','Minimal','Dark Store','Cyber','Luxury','Clean','Marketplace','Business','Colorful'];
export type ScreenStyle = { title:string;subtitle:string;footer:string;body?:string;columns:1|2|3;showEmoji:boolean;bannerUrl:string;variant?:string;galleryStyle?:'arrows'|'numbered'|'vertical';badgeStyle?:'text'|'emoji'|'none';buttonPlacement?:'before-gallery'|'after-gallery';bannerPlacement?:'before'|'after' };
const screens:Record<string,string>={products:'قائمة المنتجات',product:'تفاصيل المنتج',categories:'التصنيفات',offers:'العروض',search:'البحث',orders:'قائمة الطلبات',order:'تفاصيل الطلب',account:'حساب العميل',empty:'حالة فارغة',error:'حالة خطأ',success:'حالة نجاح',support:'الدعم',points:'النقاط',referrals:'الإحالات',coupons:'الكوبونات',notifications:'الإشعارات'};
const labels:Record<string,string>={default:'افتراضي','emoji-grid':'شبكة رموز','image-grid':'شبكة بصور',list:'قائمة',compact:'مختصر','discount-card':'بطاقات خصم','flash-offer':'عرض بارز',banner:'بانر','featured-product':'منتج مميز',arrows:'أسهم',numbered:'ترقيم',vertical:'عمودي',text:'نص',emoji:'رمز',none:'مخفي','before-gallery':'الإجراءات قبل أزرار الصور','after-gallery':'الإجراءات بعد أزرار الصور',before:'قبل الرسالة',after:'بعد الرسالة'};
const input='mt-2 w-full rounded-lg border border-[#354344] bg-[#182123] p-2';
export function TelegramScreenStyleEditor({value,onChange,ar}:{value:Record<string,ScreenStyle>;onChange:(value:Record<string,ScreenStyle>)=>void;ar:boolean}){
  return <details className="rounded-xl border border-[#354344] p-4"><summary className="cursor-pointer text-sm font-semibold">{ar?'تصميم الشاشات والحالات':'Screen and state styles'}</summary><p className="mt-3 text-xs leading-6 text-[#9aa4b4]">{ar?'الألوان والخطوط الأصلية للأزرار يحددها تطبيق Telegram؛ هذه الخيارات تضبط النص والصور وترتيب القائمة.':'Telegram controls native button colors and fonts. These options change content, images and menu order.'}</p><div className="mt-4 space-y-3">{Object.entries(screens).map(([key,label])=>{
    const style=value[key];const next=(part:Partial<ScreenStyle>)=>onChange({...value,[key]:{...(style??{title:'',subtitle:'',footer:'',columns:1,showEmoji:true,bannerUrl:''}),...part}});
    const select=(field:keyof ScreenStyle,title:string,choices:string[])=> <label className="block text-xs">{title}<select className={input} value={String(style?.[field]??choices[0])} onChange={e=>next({[field]:e.target.value})}>{choices.map(choice=><option key={choice} value={choice}>{ar?labels[choice]??choice:choice}</option>)}</select></label>;
    return <details key={key} className="rounded-lg border border-[#354344] p-3"><summary className="cursor-pointer text-sm">{ar?label:key}</summary><div className="mt-3 space-y-3">{(['title','subtitle','body','footer','bannerUrl'] as const).map(field=><label key={field} className="block text-xs">{ar?{title:'العنوان',subtitle:'الوصف المختصر',body:'محتوى إضافي',footer:'التذييل',bannerUrl:'رابط صورة الترويسة'}[field]:field}{field==='body'?<textarea className={input} maxLength={800} value={style?.body??''} onChange={e=>next({body:e.target.value})}/>:<input className={input} type={field==='bannerUrl'?'url':'text'} maxLength={field==='bannerUrl'?1500:200} value={style?.[field]??''} onChange={e=>next({[field]:e.target.value})}/>}</label>)}
      {select('bannerPlacement',ar?'موضع الترويسة':'Banner placement',['before','after'])}
      {key==='categories'&&select('variant',ar?'عرض التصنيفات':'Category layout',['default','emoji-grid','image-grid','list','compact'])}
      {key==='offers'&&select('variant',ar?'عرض العروض':'Offer layout',['default','discount-card','flash-offer','banner','featured-product'])}
      {!['categories','offers','product'].includes(key)&&select('variant',ar?'أسلوب الرسالة':'Message style',['default','list','compact'])}
      {key==='product'&&<>{select('galleryStyle',ar?'أزرار معرض الصور':'Gallery controls',['arrows','numbered','vertical'])}{select('badgeStyle',ar?'شارة الخصم':'Discount badge',['text','emoji','none'])}{select('buttonPlacement',ar?'موضع إجراءات المنتج':'Product actions',['after-gallery','before-gallery'])}</>}
      <div className="flex flex-wrap gap-4"><label className="text-xs">{ar?'أعمدة الأزرار':'Button columns'}<select value={style?.columns??1} onChange={e=>next({columns:Number(e.target.value) as 1|2|3})} className="ms-2 rounded-lg bg-[#182123] p-2"><option>1</option><option>2</option><option>3</option></select></label><label className="flex gap-2 text-xs"><input type="checkbox" checked={style?.showEmoji??true} onChange={e=>next({showEmoji:e.target.checked})}/>{ar?'إظهار الرموز':'Show emoji'}</label></div><button type="button" className="text-xs text-[#e4a09a]" onClick={()=>{const copy={...value};delete copy[key];onChange(copy);}}>{ar?'استعادة التصميم الافتراضي':'Restore default styling'}</button>
    </div></details>;
  })}</div></details>;
}
