import assert from 'node:assert/strict';
import test from 'node:test';
import { randomUUID } from 'node:crypto';
import { attendanceSchema, gradeSchema, normalizeInternalId, normalizeStudentName, safeCsvCell, teacherProfileSchema, validateTeacherImage, validTeacherDate } from './teacher-validation.ts';
test('teacher profile drafts are resumable and completion needs useful names',()=>{ assert.equal(teacherProfileSchema.parse({onboardingStep:2}).onboardingStep,2);assert.equal(teacherProfileSchema.safeParse({complete:true}).success,false);assert.equal(teacherProfileSchema.safeParse({teacherName:'معلم تجريبي',schoolName:'مدرسة تجريبية',complete:true}).success,true);assert.equal(teacherProfileSchema.safeParse({logoAssetId:'javascript:alert(1)'}).success,false); });
test('Arabic roster identifiers normalize safely and spreadsheet exports neutralize formulas',()=>{ assert.equal(normalizeInternalId(' ٠۱۲٣ '),'0123');assert.equal(normalizeStudentName('  طالب   تجريبي  '),'طالب تجريبي');for(const value of ['=1+1','+1','-2','@sum(A1)',' \t=HYPERLINK("https://example.invalid")'])assert.ok(safeCsvCell(value).startsWith('"\''));assert.equal(safeCsvCell('طالب، تجريبي'),'"طالب، تجريبي"');assert.equal(safeCsvCell('سطر "خاص"'),'"سطر ""خاص"""'); });
test('teacher dates reject normalization of invalid days and grade totals are enforced',()=>{assert.equal(validTeacherDate('2026-02-30'),false);assert.equal(validTeacherDate('2024-02-29'),true);assert.equal(validTeacherDate('2026-2-1'),false);const base={classId:randomUUID(),studentId:randomUUID(),title:'تقييم تجريبي',date:'2026-10-09',totalMarks:10};assert.equal(gradeSchema.safeParse({...base,marks:11}).success,false);assert.equal(gradeSchema.safeParse({...base,marks:null}).success,true);assert.equal(gradeSchema.safeParse({...base,marks:8,date:'2026-02-30'}).success,false);});
test('attendance rejects duplicate student entries and cross-shape payloads',()=>{const id=randomUUID(),base={classId:randomUUID(),date:'2026-10-09'};assert.equal(attendanceSchema.safeParse({...base,entries:[{studentId:id,status:'present'},{studentId:id,status:'absent'}]}).success,false);assert.equal(attendanceSchema.safeParse({...base,entries:[{studentId:id,status:'unknown'}]}).success,false);});
test('private image validation checks type, content, dimensions and size',()=>{const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/fV8AAAAASUVORK5CYII=','base64');assert.equal(validateTeacherImage(png,'image/png'),true);assert.equal(validateTeacherImage(png,'image/jpeg'),false);assert.equal(validateTeacherImage(Buffer.from('<svg onload="alert(1)"/>'),'image/png'),false);const huge=Buffer.from(png);huge.writeUInt32BE(17000,16);assert.equal(validateTeacherImage(huge,'image/png'),false);assert.equal(validateTeacherImage(Buffer.alloc(8*1024*1024+1),'image/png'),false);});
