ALTER TABLE products ADD COLUMN IF NOT EXISTS old_price numeric(12,2);
ALTER TABLE products ADD COLUMN IF NOT EXISTS warranty text NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN IF NOT EXISTS tags text[] NOT NULL DEFAULT '{}';
ALTER TABLE products ADD COLUMN IF NOT EXISTS featured boolean NOT NULL DEFAULT false;
