-- Non-destructive account onboarding and private teacher workspace.
ALTER TABLE users ADD COLUMN IF NOT EXISTS account_type text DEFAULT 'merchant';
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='users'::regclass AND conname='users_account_type_check') THEN
    ALTER TABLE users ADD CONSTRAINT users_account_type_check CHECK (account_type IS NULL OR account_type IN ('merchant','teacher'));
  END IF;
END $$;
CREATE TABLE IF NOT EXISTS teacher_profiles (owner_id text PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, data jsonb NOT NULL DEFAULT '{}', complete boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS teacher_classes (id text PRIMARY KEY, owner_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE, name text NOT NULL, data jsonb NOT NULL DEFAULT '{}', archived boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(id,owner_id));
CREATE INDEX IF NOT EXISTS teacher_classes_owner_idx ON teacher_classes(owner_id);
CREATE TABLE IF NOT EXISTS teacher_students (id text PRIMARY KEY, owner_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE, class_id text NOT NULL, name text NOT NULL, internal_id text NOT NULL DEFAULT '', notes text NOT NULL DEFAULT '', archived boolean NOT NULL DEFAULT false, removed boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(id,owner_id), FOREIGN KEY(class_id,owner_id) REFERENCES teacher_classes(id,owner_id));
CREATE INDEX IF NOT EXISTS teacher_students_owner_class_idx ON teacher_students(owner_id,class_id);
CREATE UNIQUE INDEX IF NOT EXISTS teacher_students_internal_unique ON teacher_students(owner_id,class_id,internal_id) WHERE internal_id<>'' AND removed=false;
CREATE TABLE IF NOT EXISTS teacher_records (id text PRIMARY KEY, owner_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE, kind text NOT NULL CHECK(kind IN ('attendance','grades','tasks','lessons','questions','assessments')), class_id text, student_id text, dedupe_key text, data jsonb NOT NULL, archived boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(class_id,owner_id) REFERENCES teacher_classes(id,owner_id), FOREIGN KEY(student_id,owner_id) REFERENCES teacher_students(id,owner_id), UNIQUE(owner_id,kind,dedupe_key));
CREATE INDEX IF NOT EXISTS teacher_records_owner_kind_idx ON teacher_records(owner_id,kind);
CREATE TABLE IF NOT EXISTS teacher_assets (id text PRIMARY KEY, owner_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE, mime_type text NOT NULL CHECK(mime_type IN ('image/jpeg','image/png','image/webp')), size integer NOT NULL CHECK(size>0 AND size<=8388608), content_base64 text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(id,owner_id));
CREATE INDEX IF NOT EXISTS teacher_assets_owner_idx ON teacher_assets(owner_id);
CREATE TABLE IF NOT EXISTS teacher_exams (id text PRIMARY KEY, owner_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE, title text NOT NULL, document jsonb NOT NULL, source_asset_id text, version integer NOT NULL DEFAULT 1 CHECK(version>0), is_template boolean NOT NULL DEFAULT false, archived boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(source_asset_id,owner_id) REFERENCES teacher_assets(id,owner_id));
CREATE INDEX IF NOT EXISTS teacher_exams_owner_idx ON teacher_exams(owner_id);
CREATE TABLE IF NOT EXISTS teacher_rules (id text PRIMARY KEY, owner_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE, name text NOT NULL, type text NOT NULL CHECK(type IN ('upcoming','absence','grading','weekly','draft','recurring')), enabled boolean NOT NULL DEFAULT true, config jsonb NOT NULL, next_run_at timestamptz, last_run_at timestamptz, last_result text, error text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS teacher_rules_next_run_idx ON teacher_rules(enabled,next_run_at);
CREATE TABLE IF NOT EXISTS teacher_reminders (id text PRIMARY KEY, owner_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE, rule_id text REFERENCES teacher_rules(id) ON DELETE SET NULL, title text NOT NULL, body text NOT NULL, read boolean NOT NULL DEFAULT false, dedupe_key text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(owner_id,dedupe_key));
CREATE TABLE IF NOT EXISTS teacher_rule_runs (id text PRIMARY KEY, rule_id text NOT NULL REFERENCES teacher_rules(id) ON DELETE CASCADE, scheduled_at timestamptz NOT NULL, result text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(rule_id,scheduled_at));
