import assert from 'node:assert/strict';
import test from 'node:test';
import { randomUUID } from 'node:crypto';
import { eq, inArray } from 'drizzle-orm';
import { db, pool, usersTable, storesTable, storeSettingsTable, customersTable, growthResourcesTable, growthJobsTable, customerLedgerTable, couponsTable, telegramBotsTable, productsTable, categoriesTable, ordersTable, orderItemsTable } from '@workspace/db';
import { enqueueGrowthEvent, processGrowthJobs, queueActions, touchCustomer, customerFacts } from '../src/lib/growth-service';
import { defaultGrowthConfiguration, parseGrowthConfiguration, type GrowthAction } from '../src/lib/growth-configuration';
import { encryptBotToken, sha256 } from '../src/lib/security';

test('durable growth execution deduplicates events, preserves order, assigns coupons and records delivery failures', async () => {
  assert.equal(new URL(process.env.DATABASE_URL!).hostname, 'ep-summer-recipe-b21ls93d-pooler.c-6.eu-central-1.aws.neon.tech');
  const ownerId = randomUUID(); const storeId = randomUUID(); const outsiderStore = randomUUID(); const couponId = randomUUID(); const resourceId = randomUUID();
  const originalFetch = globalThis.fetch; let deliveryMode = 'ok'; const sent: Record<string, unknown>[] = [];
  globalThis.fetch = async (url, init) => {
    assert.match(String(url), /^https:\/\/api\.telegram\.org\/botgrowth-test-token\/send(?:Message|Photo)$/);
    sent.push(JSON.parse(String(init?.body)));
    return new Response(JSON.stringify(deliveryMode === 'ok' ? { ok: true } : deliveryMode === 'blocked' ? { ok: false, error_code: 403 } : { ok: false, error_code: 429, parameters: { retry_after: 180 } }), { status: deliveryMode === 'ok' ? 200 : deliveryMode === 'blocked' ? 403 : 429, headers: { 'content-type': 'application/json' } });
  };
  const finishJobs = async () => { for (let attempt = 0; attempt < 40; attempt++) { const pending = (await db.select().from(growthJobsTable).where(eq(growthJobsTable.storeId, storeId))).filter(j => j.status === 'queued' && j.availableAt.getTime() <= Date.now()); if (!pending.length) return; await processGrowthJobs(storeId); await new Promise(resolve => setTimeout(resolve, 1250)); } throw Error('Test jobs did not finish'); };
  try {
    await db.insert(usersTable).values({ id: ownerId, name: 'Growth test', email: `growth-${ownerId}@example.invalid`, passwordHash: 'no-login' });
    await db.insert(storesTable).values([storeId, outsiderStore].map(id => ({ id, ownerId, name: 'Growth test store', slug: `growth-${id}` })));
    await db.insert(storeSettingsTable).values([storeId, outsiderStore].map(id => ({ storeId: id, couponsEnabled: true, pointsEnabled: true, settings: { plan: { code: 'BUSINESS' } } })));
    const config = defaultGrowthConfiguration('journey'); config.actions = [{ ...config.actions[0], type: 'ADD_POINTS', amount: 10 }, { ...config.actions[0], type: 'ADD_TAG', target: 'welcome' }];
    await db.insert(growthResourcesTable).values({ id: resourceId, storeId, kind: 'journey', name: 'Welcome journey', enabled: true, configuration: config as unknown as Record<string, unknown> });
    await Promise.all([touchCustomer({ storeId, userId: 88901, chatId: 88901, name: 'Customer' }), touchCustomer({ storeId, userId: 88901, chatId: 88901, name: 'Customer' })]);
    const [customer] = await db.select().from(customersTable).where(eq(customersTable.storeId, storeId));
    const registered = (await db.select().from(growthJobsTable).where(eq(growthJobsTable.storeId, storeId))).filter(j => j.payload.trigger === 'USER_REGISTERED');
    assert.equal(registered.length, 1, 'registration produces one durable event');
    await finishJobs();
    let [current] = await db.select().from(customersTable).where(eq(customersTable.id, customer.id)); assert.equal(current.points, 10); assert.deepEqual(current.tags, ['welcome']);
    assert.equal((await db.select().from(customerLedgerTable).where(eq(customerLedgerTable.customerId, customer.id))).length, 1);
    await db.transaction(async tx => { await enqueueGrowthEvent(tx, { storeId, telegramUserId: customer.telegramUserId, trigger: 'USER_REGISTERED', eventId: customer.id }); }); await finishJobs();
    [current] = await db.select().from(customersTable).where(eq(customersTable.id, customer.id)); assert.equal(current.points, 10, 'event replay never repeats ledger credit');
    const pointsConfig = defaultGrowthConfiguration('automation'); pointsConfig.trigger = 'POINTS_EARNED'; pointsConfig.actions = [{ ...pointsConfig.actions[0], type: 'ADD_POINTS', amount: 1 }];
    assert.equal(parseGrowthConfiguration(pointsConfig), null, 'points-earned rules cannot create a recursive points credit or debit');
    const depthEventId = randomUUID();
    await db.transaction(tx => enqueueGrowthEvent(tx, { storeId, telegramUserId: customer.telegramUserId, trigger: 'POINTS_EARNED', eventId: depthEventId, depth: 4 }));
    assert.equal((await db.select().from(growthJobsTable).where(eq(growthJobsTable.storeId, storeId))).filter(job => job.dedupeKey === `event:POINTS_EARNED:${depthEventId}`).length, 0, 'events beyond the maximum depth are never queued');
    const vipConfig = defaultGrowthConfiguration('automation'); vipConfig.trigger = 'VIP_LEVEL_CHANGED'; vipConfig.condition = { field: 'VIP_LEVEL', operator: '>=', value: 2 }; vipConfig.actions = [{ ...vipConfig.actions[0], type: 'ADD_TAG', target: 'vip-change' }];
    const vipResourceId = randomUUID(); await db.insert(growthResourcesTable).values({ id: vipResourceId, storeId, kind: 'automation', name: 'VIP change automation', enabled: true, configuration: vipConfig as unknown as Record<string, unknown> });
    const vipEventId = randomUUID(); await db.transaction(async tx => { await tx.update(customersTable).set({ vipLevel: 2 }).where(eq(customersTable.id, customer.id)); await enqueueGrowthEvent(tx, { storeId, telegramUserId: customer.telegramUserId, trigger: 'VIP_LEVEL_CHANGED', eventId: vipEventId }); }); await finishJobs();
    [current] = await db.select().from(customersTable).where(eq(customersTable.id, customer.id)); assert.ok(current.tags.includes('vip-change'), 'VIP change automation evaluates the actual updated level');
    await db.transaction(tx => enqueueGrowthEvent(tx, { storeId, telegramUserId: customer.telegramUserId, trigger: 'VIP_LEVEL_CHANGED', eventId: vipEventId })); await finishJobs();
    assert.equal((await db.select().from(growthJobsTable).where(eq(growthJobsTable.resourceId, vipResourceId))).length, 1, 'replayed VIP events produce a single action');
    const bad: GrowthAction = { ...config.actions[0], type: 'REMOVE_POINTS', amount: 100 }; const next: GrowthAction = { ...config.actions[0], type: 'ADD_TAG', target: 'must-not-run' };
    await db.transaction(tx => queueActions(tx, { storeId, resourceId, customerId: customer.id, actions: [bad, next], event: {}, dedupe: 'failure-branch' }));
    const [failed] = (await db.select().from(growthJobsTable).where(eq(growthJobsTable.storeId, storeId))).filter(j => j.dedupeKey.startsWith('failure-branch:'));
    await db.update(growthJobsTable).set({ attempts: 2 }).where(eq(growthJobsTable.id, failed.id)); await finishJobs();
    [current] = await db.select().from(customersTable).where(eq(customersTable.id, customer.id)); assert.equal(current.tags.includes('must-not-run'), false, 'failed predecessor stops dependent action');
    await db.insert(couponsTable).values({ id: couponId, storeId, code: `TEST_${couponId.slice(0, 8)}`, percent: 10 });
    await db.insert(telegramBotsTable).values({ storeId, encryptedToken: encryptBotToken('growth-test-token'), tokenHash: sha256('growth-test-token-' + storeId), telegramBotId: '88900', status: 'connected' });
    await db.transaction(tx => queueActions(tx, { storeId, resourceId, customerId: customer.id, actions: [{ ...config.actions[0], type: 'SEND_COUPON', target: couponId, text: 'Thanks {{customer}} at {{store}}' }], event: {}, dedupe: 'coupon' })); await finishJobs();
    [current] = await db.select().from(customersTable).where(eq(customersTable.id, customer.id)); assert.equal(current.state.couponId, couponId); assert.equal((await customerFacts(current)).HAS_COUPON, true); assert.match(String(sent[0].text), /TEST_/);
    await db.update(couponsTable).set({ enabled: false }).where(eq(couponsTable.id, couponId)); assert.equal((await customerFacts(current)).HAS_COUPON, false, 'disabled coupon no longer counts in rules');
    deliveryMode = 'limited'; await db.transaction(tx => queueActions(tx, { storeId, resourceId, customerId: customer.id, actions: [{ ...config.actions[0], type: 'SEND_MESSAGE', text: 'Rate limit check' }], event: {}, dedupe: 'rate-limit' })); await finishJobs();
    const [limited] = (await db.select().from(growthJobsTable).where(eq(growthJobsTable.storeId, storeId))).filter(j => j.dedupeKey.startsWith('rate-limit:')); assert.equal(limited.status, 'queued'); assert.ok(limited.availableAt.getTime() > Date.now() + 170000, 'Telegram retry_after is respected');
    deliveryMode = 'blocked'; await db.transaction(tx => queueActions(tx, { storeId, resourceId, customerId: customer.id, actions: [{ ...config.actions[0], type: 'SEND_MESSAGE', text: 'Blocked check' }], event: {}, dedupe: 'blocked' })); await finishJobs();
    [current] = await db.select().from(customersTable).where(eq(customersTable.id, customer.id)); assert.equal(current.optedIn, false); const [blocked] = (await db.select().from(growthJobsTable).where(eq(growthJobsTable.storeId, storeId))).filter(j => j.dedupeKey.startsWith('blocked:')); assert.equal(blocked.status, 'failed'); assert.equal(blocked.attempts, 1, 'permanent Telegram failure is not retried');
    const deliveryCountAfterOptOut = sent.length;
    await db.transaction(tx => queueActions(tx, { storeId, resourceId, customerId: customer.id, actions: [{ ...config.actions[0], type: 'SEND_MESSAGE', text: 'Do not send to opted-out customer' }], event: {}, dedupe: 'already-opted-out' })); await finishJobs();
    const [optedOutJob] = (await db.select().from(growthJobsTable).where(eq(growthJobsTable.storeId, storeId))).filter(j => j.dedupeKey.startsWith('already-opted-out:'));
    assert.equal(optedOutJob.status, 'failed'); assert.equal(optedOutJob.attempts, 1, 'opt-out known before delivery is permanent'); assert.equal(sent.length, deliveryCountAfterOptOut, 'an opted-out customer is never sent another message');
    deliveryMode = 'ok';
    const vipId = randomUUID(); const optedOutId = randomUUID(); const foreignCustomerId = randomUUID(); const broadcastId = randomUUID(); const segmentId = randomUUID();
    const [vip] = await db.insert(customersTable).values([{ id: vipId, storeId, telegramUserId: '88902', telegramChatId: '88902', name: 'Selected VIP', vipLevel: 3 }, { id: optedOutId, storeId, telegramUserId: '88903', telegramChatId: '88903', name: 'Stopped VIP', vipLevel: 3, optedIn: false }]).returning();
    const privateCategoryId = randomUUID(); const privateProductId = randomUUID(); const privateOrderId = randomUUID();
    await db.insert(categoriesTable).values({ id: privateCategoryId, storeId, name: 'Private order category' });
    await db.insert(productsTable).values({ id: privateProductId, storeId, categoryId: privateCategoryId, name: 'Private ordered product', price: '10', isPublished: true });
    await db.insert(ordersTable).values({ id: privateOrderId, storeId, telegramUserId: vip.telegramUserId, telegramChatId: vip.telegramChatId, customerName: vip.name, currency: 'SAR', total: '10' });
    await db.insert(orderItemsTable).values({ id: randomUUID(), orderId: privateOrderId, productId: privateProductId, productName: 'Private ordered product', unitPrice: '10', quantity: 1, lineTotal: '10' });
    assert.deepEqual((await customerFacts(vip, { orderId: privateOrderId })).PRODUCT, [privateProductId], 'order conditions read actual products for the order owner');
    assert.deepEqual((await customerFacts(customer, { orderId: privateOrderId })).PRODUCT, [], 'another customer cannot inherit order product conditions');
    assert.deepEqual((await customerFacts(customer, { orderId: privateOrderId })).CATEGORY, [], 'another customer cannot inherit order category conditions');
    await db.insert(customersTable).values({ id: foreignCustomerId, storeId: outsiderStore, telegramUserId: '88904', telegramChatId: '88904', name: 'Foreign VIP', vipLevel: 3 });
    const broadcast = defaultGrowthConfiguration('broadcast'); broadcast.audience = { type: 'selected', segmentId: '', minimum: 1, inactivityDays: 14, customerIds: [customer.id, vipId, optedOutId, foreignCustomerId] }; broadcast.condition = { field: 'VIP_LEVEL', operator: '>=', value: 3 };
    await db.insert(growthResourcesTable).values({ id: broadcastId, storeId, kind: 'broadcast', name: 'Selected VIP campaign', status: 'queued', configuration: broadcast as unknown as Record<string, unknown> });
    const prepareId = randomUUID(); await db.insert(growthJobsTable).values({ id: prepareId, storeId, resourceId: broadcastId, dedupeKey: 'prepare:selected-test', payload: { type: 'PREPARE', runId: 'selected-test' } });
    const beforeBroadcast = sent.length; await finishJobs(); assert.equal(sent.length, beforeBroadcast + 1); assert.equal(sent.at(-1)?.chat_id, '88902', 'selected audience applies actual VIP rule and opt-out');
    const [attributed] = await db.select().from(customersTable).where(eq(customersTable.id, vipId)); assert.equal((await customerFacts(attributed)).CAMPAIGN, broadcastId, 'successful broadcast supplies durable campaign context');
    const attributedState = attributed.state.currentCampaign as Record<string, unknown>;
    await db.update(customersTable).set({ state: { ...attributed.state, currentCampaign: { ...attributedState, jobId: randomUUID() } } }).where(eq(customersTable.id, vipId));
    const [forgedDelivery] = await db.select().from(customersTable).where(eq(customersTable.id, vipId)); assert.equal((await customerFacts(forgedDelivery)).CAMPAIGN, '', 'campaign state requires a real successful delivery to this customer');
    const attributionJobId = String(attributedState.jobId);
    await db.update(customersTable).set({ state: attributed.state }).where(eq(customersTable.id, vipId));
    await db.update(growthJobsTable).set({ status: 'failed' }).where(eq(growthJobsTable.id, attributionJobId));
    const [failedDeliveryProof] = await db.select().from(customersTable).where(eq(customersTable.id, vipId)); assert.equal((await customerFacts(failedDeliveryProof)).CAMPAIGN, '', 'a failed job cannot prove campaign delivery');
    await db.update(growthJobsTable).set({ status: 'completed' }).where(eq(growthJobsTable.id, attributionJobId));
    await db.update(customersTable).set({ state: { ...attributed.state, currentCampaign: { ...attributedState, expiresAt: new Date(Date.now() - 1).toISOString() } } }).where(eq(customersTable.id, vipId));
    const [expired] = await db.select().from(customersTable).where(eq(customersTable.id, vipId)); assert.equal((await customerFacts(expired)).CAMPAIGN, '', 'expired campaign attribution fails closed');
    await db.update(customersTable).set({ state: { ...attributed.state, currentCampaign: { ...attributedState, resourceId } } }).where(eq(customersTable.id, vipId));
    const [wrongKind] = await db.select().from(customersTable).where(eq(customersTable.id, vipId)); assert.equal((await customerFacts(wrongKind)).CAMPAIGN, '', 'nonbroadcast resource cannot supply campaign identity');
    const foreignBroadcast = randomUUID(); await db.insert(growthResourcesTable).values({ id: foreignBroadcast, storeId: outsiderStore, kind: 'broadcast', name: 'Foreign campaign', status: 'completed', configuration: broadcast as unknown as Record<string, unknown> });
    await db.update(customersTable).set({ state: { ...attributed.state, currentCampaign: { ...attributedState, resourceId: foreignBroadcast } } }).where(eq(customersTable.id, vipId));
    const [foreign] = await db.select().from(customersTable).where(eq(customersTable.id, vipId)); assert.equal((await customerFacts(foreign)).CAMPAIGN, '', 'cross-store attribution never affects visibility');
    await db.update(customersTable).set({ state: attributed.state }).where(eq(customersTable.id, vipId));
    await db.update(growthJobsTable).set({ status: 'queued', attempts: 0 }).where(eq(growthJobsTable.id, prepareId)); await finishJobs(); assert.equal(sent.length, beforeBroadcast + 1, 'preparation replay cannot duplicate delivered actions');
    const retryBroadcast = randomUUID(); await db.insert(growthResourcesTable).values({ id: retryBroadcast, storeId, kind: 'broadcast', name: 'Retry campaign', status: 'running', configuration: broadcast as unknown as Record<string, unknown> });
    deliveryMode = 'limited'; await db.transaction(tx => queueActions(tx, { storeId, resourceId: retryBroadcast, customerId: vipId, actions: broadcast.actions, event: { campaignId: retryBroadcast }, dedupe: 'attribution-retry' })); await finishJobs();
    const [retryCustomer] = await db.select().from(customersTable).where(eq(customersTable.id, vipId)); assert.equal((await customerFacts(retryCustomer)).CAMPAIGN, broadcastId, 'failed delivery never overwrites prior campaign context');
    const [retryJob] = (await db.select().from(growthJobsTable).where(eq(growthJobsTable.storeId, storeId))).filter(j => j.dedupeKey.startsWith('attribution-retry:')); await db.update(growthJobsTable).set({ availableAt: new Date() }).where(eq(growthJobsTable.id, retryJob.id));
    deliveryMode = 'ok'; await finishJobs(); const [retriedCustomer] = await db.select().from(customersTable).where(eq(customersTable.id, vipId)); assert.equal((await customerFacts(retriedCustomer)).CAMPAIGN, retryBroadcast, 'successful retry updates campaign context');
    await db.insert(growthResourcesTable).values({ id: segmentId, storeId, kind: 'segment', name: 'All customer segment', enabled: true, configuration: defaultGrowthConfiguration('segment') as unknown as Record<string, unknown> });
    assert.ok((await customerFacts(vip)).CUSTOMER_SEGMENT.includes(segmentId));
    await db.transaction(tx => queueActions(tx, { storeId, resourceId, customerId: vipId, actions: [{ ...config.actions[0], type: 'REMOVE_SEGMENT', target: segmentId }], event: {}, dedupe: 'remove-segment' })); await finishJobs();
    const [removed] = await db.select().from(customersTable).where(eq(customersTable.id, vipId)); assert.equal((await customerFacts(removed)).CUSTOMER_SEGMENT.includes(segmentId), false, 'explicit removal overrides matching dynamic segment');
    await db.transaction(tx => queueActions(tx, { storeId, resourceId, customerId: vipId, actions: [{ ...config.actions[0], type: 'ADD_SEGMENT', target: segmentId }], event: {}, dedupe: 'add-segment' })); await finishJobs();
    const [added] = await db.select().from(customersTable).where(eq(customersTable.id, vipId)); assert.ok((await customerFacts(added)).CUSTOMER_SEGMENT.includes(segmentId));
  } finally {
    globalThis.fetch = originalFetch;
    await db.delete(customerLedgerTable).where(inArray(customerLedgerTable.storeId, [storeId, outsiderStore]));
    await db.delete(growthJobsTable).where(inArray(growthJobsTable.storeId, [storeId, outsiderStore]));
    await db.delete(growthResourcesTable).where(inArray(growthResourcesTable.storeId, [storeId, outsiderStore]));
    await db.delete(couponsTable).where(eq(couponsTable.storeId, storeId));
    await db.delete(customersTable).where(inArray(customersTable.storeId, [storeId, outsiderStore]));
    await db.delete(storesTable).where(inArray(storesTable.id, [storeId, outsiderStore]));
    await db.delete(usersTable).where(eq(usersTable.id, ownerId)); await pool.end();
  }
});
